DEFRA/rod-licensing

README.md
docker/README.md
docker/services.build.yml

- Added guidance for infrastructure and services
- Fixed minor problem with building development services locally

Add guidance for building and running docker services locally

---

packages/gafl-webapp-service/package-lock.json
packages/gafl-webapp-service/package.json

Add semver to package dependencies - otherwise in production mode it is not found as its declared as a dev dependency

Add explicit frontend dependency for semver otherwise it isn't installed in production but required by @hapi/scooter

---

packages/gafl-webapp-service/src/constants.js
packages/gafl-webapp-service/src/handlers/controller-handler.js
packages/gafl-webapp-service/src/pages/concessions/benefit-check/result-function.js
packages/gafl-webapp-service/src/pages/concessions/blue-badge-check/result-function.js
packages/gafl-webapp-service/src/pages/concessions/date-of-birth/result-function.js
packages/gafl-webapp-service/src/pages/concessions/junior-licence/__tests__/junior-licence.spec.js
packages/gafl-webapp-service/src/pages/concessions/junior-licence/result-function.js
packages/gafl-webapp-service/src/pages/contact/address/lookup/result-function.js
packages/gafl-webapp-service/src/pages/contact/contact/result-function.js
packages/gafl-webapp-service/src/pages/licence-details/licence-start-date/result-function.js
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/result-function.js
packages/gafl-webapp-service/src/pages/licence-details/licence-type/result-function.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
packages/gafl-webapp-service/src/processors/__tests__/concession-helper-spec.js
packages/gafl-webapp-service/src/processors/concession-helper.js
packages/gafl-webapp-service/src/routes/journey-definition.js

Just the changes to existing journey with disabled concessions enabled for juniors and seniors.

Allow senior and juniors access to disabled concessions

---

packages/business-rules-lib/src/validators/__tests__/contact.spec.js
packages/business-rules-lib/src/validators/contact.js
packages/gafl-webapp-service/package-lock.json
packages/gafl-webapp-service/src/pages/concessions/benefit-ni-number/benefit-ni-number.njk
packages/gafl-webapp-service/src/pages/concessions/benefit-ni-number/route.js

Add an NI number validator to the business rules and use it on the current NI page

Add an NI number validator

---

packages/connectors-lib/src/sales-api-connector.js
packages/pocl-job/src/staging/create-transactions.js
packages/pocl-job/src/staging/finalise-transactions.js
packages/pocl-job/src/transport/ftp-to-s3.js
packages/sales-api-service/src/services/contacts.service.js
packages/sales-api-service/src/services/transactions/create-transaction.js
packages/sales-api-service/src/services/transactions/finalise-transaction.js
packages/sales-api-service/src/services/transactions/process-transaction-queue.js
packages/sales-api-service/src/services/transactions/retrieve-transaction.js
packages/sqs-receiver-service/src/__mocks__/aws-sdk.js
packages/sqs-receiver-service/src/__tests__/read-queue.spec.js
packages/sqs-receiver-service/src/delete-messages.js
packages/sqs-receiver-service/src/process-message.js
packages/sqs-receiver-service/src/read-queue.js
packages/sqs-receiver-service/src/receiver.js

- Fix issue with SQS receiver which was unnecessarily imposing a delay on polling even if messages were received
- Ensure Sales API connector using the `Accept: application/json` header (AWS ALB was returning an HTML response)
- Revise logging for the POCL job and the Sales API to facilitate easier debugging

Fix issues in SQS receiver and Sales API connector

---

packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
packages/connectors-lib/src/sales-api-connector.js
packages/gafl-webapp-service/src/processors/payment.js
packages/gafl-webapp-service/src/services/payment/govuk-pay-service.js
packages/pocl-job/src/pocl-processor.js
packages/pocl-job/src/staging/pocl-data-staging.js
packages/sales-api-service/src/server/routes/reference-data.js
packages/sales-api-service/src/server/routes/transactions.js
packages/sales-api-service/src/services/contacts.service.js
packages/sales-api-service/src/services/exceptions/exceptions.service.js
packages/sales-api-service/src/services/paymentjournals/payment-journals.service.js
packages/sales-api-service/src/services/transactions/create-transaction.js
packages/sales-api-service/src/services/transactions/finalise-transaction.js
packages/sqs-receiver-service/src/__tests__/process-message.spec.js
packages/sqs-receiver-service/src/delete-messages.js
packages/sqs-receiver-service/src/process-message.js

- Add fallback method to sales api connector to parse text if json parse fails
- Revise logging output to simplify tracking in AWS CloudWatch logs

Add fallback response parser method to Sales API connector and revise logging ouput

---

packages/gafl-webapp-service/src/plugins.js
packages/gafl-webapp-service/src/server.js
packages/gafl-webapp-service/src/session-cache/session-manager.js

Added headers as a result of the OWASP ZAP Scan

Security headers

---

packages/connectors-lib/package-lock.json
packages/connectors-lib/package.json
packages/connectors-lib/src/__tests__/document-client-decorator.spec.js
packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
packages/connectors-lib/src/documentclient-decorator.js
packages/connectors-lib/src/sales-api-connector.js
packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-sales-api-failure.spec.js
packages/pocl-job/src/io/db.js
packages/pocl-job/src/staging/__tests__/create-transactions.spec.js
packages/pocl-job/src/staging/__tests__/finalise-transactions.spec.js
packages/pocl-job/src/staging/create-transactions.js
packages/pocl-job/src/staging/finalise-transactions.js
packages/sales-api-service/src/services/transactions/create-transaction.js
packages/sqs-receiver-service/src/__tests__/receiver.spec.js

- Add handling for UnprocessedItems returned from DynamoDB batchWrite
- Improve POCL error handling when communicating with the Sales API

Improve reliability and error handling of the POCL processor 

---

packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk
packages/gafl-webapp-service/src/pages/contact/address/entry/address-entry.njk
packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
packages/gafl-webapp-service/src/pages/contact/address/select/address-select.njk
packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
packages/gafl-webapp-service/src/pages/contact/newsletter/newsletter.njk
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
packages/gafl-webapp-service/src/processors/refdata-helper.js

Review of content with Howard has shown inconsistent use of language around personal pronouns. We have now used 'you' throughout the service.

QA review of content

---

package.json
packages/sales-api-service/package-lock.json
packages/sales-api-service/package.json
packages/sales-api-service/src/__mocks__/ioredis.js
packages/sales-api-service/src/services/__tests__/ioredis.spec.js
packages/sales-api-service/src/services/__tests__/permissions.service.spec.js
packages/sales-api-service/src/services/ioredis.service.js
packages/sales-api-service/src/services/permissions.service.js
sonar-project.properties

- Permission numbers now generated based on a sequence no stored in redis
- Last digit of permission is now a checksum based on luhn mod 10 algorithm

Update permission number generator to use a sequence and add a checksum

---

scripts/travis/deploy.sh

Script now supports creating a merge commit to master using the following commit messages:
- SEMVER-MAJOR - to force semver major update on master
- SEMVER-PATCH - to force semver patch update on master
As before, anything else will result in a semver-minor update on master

Improve versioning control in travis deploy script when merging to master

---

packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk

https://eaflood.atlassian.net/browse/IWTF-1362
Note: the timeout is 3 hours not 1 hour

Changes to the accessibility statement

---

packages/gafl-webapp-service/assets/sass/rod-licensing/_general.scss
packages/gafl-webapp-service/src/handlers/renewal-start-date-validation-handler.js
packages/gafl-webapp-service/src/pages/layout/layout.njk
packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/__tests__/renewal-start-date.spec.js
packages/gafl-webapp-service/src/processors/renewals-write-cache.js
packages/gafl-webapp-service/src/server.js

(1) Add telesales clear link
(2) Fix renewals time comparator to use local time.

Added telesales new customer button (#438)

---

packages/gafl-webapp-service/src/handlers/error-handler.js
packages/gafl-webapp-service/src/pages/errors/client-error.njk
packages/gafl-webapp-service/src/pages/terms-and-conditions/terms-and-conditions.njk

Add warning about back button on payment back and disable try again button

IWTF-1517: Back button behaviour on payment pages

---

packages/gafl-webapp-service/src/pages/errors/client-error.njk

https://eaflood.atlassian.net/browse/IWTF-1718
Fix for accessibility issues on the a problem has occurred page

Accessibility issues on the a problem has occurred page

---

.github/workflows/build.yml

https://eaflood.atlassian.net/browse/IWTF-1761
Github actions sonar checks for coverage is failing for rod-licensing on develop.

Github actions for sonar code coverage failing for rod-licensing

---

packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
packages/gafl-webapp-service/src/processors/__tests__/analytics.spec.js
packages/gafl-webapp-service/src/processors/analytics.js

https://eaflood.atlassian.net/browse/IWTF-1638
Update analytics attribution

Attribution is always logging warning

---

packages/gafl-webapp-service/src/handlers/result-functions.js
packages/gafl-webapp-service/src/handlers/update-transaction-functions.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/licence-confirmation-method.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/licence-confirmation-method.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/result-function.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/route.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/update-transaction.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/licence-fulfilment.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/licence-fulfilment.njk
packages/gafl-webapp-service/src/routes/journey-definition.js
packages/gafl-webapp-service/src/routes/routes.js
packages/gafl-webapp-service/src/uri.js

https://eaflood.atlassian.net/browse/IWTF-1928
Following the licence fulfilment screen, the licence confirmation method screen should be shown. This is also called where should we send your licence?

Licence confirmation method - where should we send your licence? screen

---

packages/gafl-webapp-service/src/handlers/update-transaction-functions.js
packages/gafl-webapp-service/src/pages/contact/contact/route.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/licence-confirmation-method.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/licence-confirmation-method.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/route.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/update-transaction.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/licence-fulfilment.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/route.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/update-transaction.js
packages/gafl-webapp-service/src/processors/__tests__/contact-validator.spec.js
packages/gafl-webapp-service/src/processors/contact-validator.js
packages/gafl-webapp-service/src/processors/mapping-constants.js
packages/sales-api-service/src/schema/contact.schema.js

https://eaflood.atlassian.net/browse/IWTF-1963
Licence confirmation method screen if selecting paper licence

Licence confirmation method paper

---

packages/gafl-webapp-service/src/pages/contact/contact/__tests__/contact.spec.js
packages/gafl-webapp-service/src/pages/contact/contact/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
packages/gafl-webapp-service/src/pages/contact/contact/update-transaction.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/licence-confirmation-method.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/route.js
packages/gafl-webapp-service/src/pages/contact/newsletter/__tests__/newsletter.spec.js
packages/gafl-webapp-service/src/pages/contact/newsletter/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/contact/newsletter/update-transaction.js
packages/gafl-webapp-service/src/pages/licence-details/licence-length/update-transaction.js
packages/gafl-webapp-service/src/routes/__tests__/back-links.spec.js
packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-1929
There are two versions of the contact page, one for paper licences and one for digital

Contact page for digital licence

---

.github/workflows/build.yml
packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
packages/gafl-webapp-service/src/pages/order-complete/route.js

https://eaflood.atlassian.net/browse/IWTF-1930
There is different text on the order complete page depending on whether the Angler has opted for a paperless licence or not

Order Complete screen text for digital licence

---

packages/gafl-webapp-service/src/pages/contact/contact/update-transaction.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/licence-confirmation-method.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/update-transaction.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/licence-fulfilment.spec.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk
packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-1932
As an angler I want to be able to check how my licence will be delivered to me

Check your details screen should contain licence delivery method

---

scripts/github/deploy.sh

Updated the version script to use `git describe` to get the latest tag for a particular branch

Fix deployment script

---

.github/workflows/build.yml
scripts/github/deploy.sh

https://eaflood.atlassian.net/browse/IWTF-1971
Version script doesn't handle single quote character in commit message

Version script doesn't handle single quote character in commit message

---

.github/workflows/build.yml
scripts/github/deploy.sh

https://eaflood.atlassian.net/browse/IWTF-1971
Error with the script not being able to increment tags.

Error with the script not being able to increment tags

---

docker/README.md
package-lock.json
package.json
packages/dynamics-lib/src/client/__tests__/entity-manager.spec.js
packages/dynamics-lib/src/client/entity-manager.js
packages/fulfilment-job/src/staging/__tests__/create-part-files.spec.js
packages/fulfilment-job/src/staging/__tests__/deliver-fulfilment-files.spec.js
packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry-spec.js
packages/gafl-webapp-service/src/pages/contact/address/entry/route.js
packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
packages/gafl-webapp-service/src/processors/__tests__/analytics.spec.js
packages/gafl-webapp-service/src/processors/__tests__/refdata-helper.spec.js
packages/gafl-webapp-service/src/processors/api-transaction.js
packages/gafl-webapp-service/src/processors/refdata-helper.js
packages/pocl-job/src/transport/__tests__/ftp-to-s3.spec.js
packages/pocl-job/src/transport/ftp-to-s3.js
packages/sales-api-service/src/schema/transaction.schema.js
packages/sales-api-service/src/schema/validators/__tests__/validators.spec.js
packages/sales-api-service/src/schema/validators/validators.js
packages/sales-api-service/src/server/routes/__tests__/transaction-files.spec.js
packages/sales-api-service/src/services/exceptions/__tests__/exceptions.service.spec.js
packages/sales-api-service/src/services/transactions/process-transaction-queue.js

https://eaflood.atlassian.net/browse/IWTF-2064
Fix error when running prettier - Environment key "es2021" is unknown

Fix issue with prettier

---

packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk

Fix: Updates Accessibility Statement headings use correct semantics

---

packages/dynamics-lib/src/entities/__tests__/contact.entity.spec.js
packages/dynamics-lib/src/entities/contact.entity.js
packages/gafl-webapp-service/src/__mocks__/mock-journeys.js
packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
packages/gafl-webapp-service/src/pages/contact/contact/update-transaction.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/licence-confirmation-method.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/licence-fulfilment.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/update-transaction.js
packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
packages/gafl-webapp-service/src/pages/renewals/identify/__mocks__/data/authentication-result.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
packages/gafl-webapp-service/src/processors/__tests__/api-transaction.spec.js
packages/gafl-webapp-service/src/processors/mapping-constants.js
packages/gafl-webapp-service/src/services/payment/__test__/data/mock-transaction.js
packages/sales-api-service/src/__mocks__/test-data.js
packages/sales-api-service/src/schema/contact.schema.js
packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js

https://eaflood.atlassian.net/browse/IWTF-2025
Store postalFulfilment flag in Dynamics

Store postalFulfilment flag in Dynamics

---

packages/sales-api-service/src/__mocks__/test-data.js
packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
packages/sales-api-service/src/services/transactions/process-transaction-queue.js

https://eaflood.atlassian.net/browse/IWTF-1931
Create fulfilment from sales api if postalFulfilment flag is true

Create fulfilment from sales api

---

packages/gafl-webapp-service/src/pages/macros/standard-form.njk

Fix: Moves Continue button outside of fieldset

---

packages/gafl-webapp-service/src/pages/macros/pricing-summary.njk

IWTF-2145
* Adds status role to div

Fix: Makes cost summary panel screen reader friendly

---

packages/gafl-webapp-service/src/pages/order-complete/__tests__/order-complete.spec.js
packages/gafl-webapp-service/src/pages/order-complete/route.js
packages/gafl-webapp-service/src/routes/journey-definition.js
packages/gafl-webapp-service/src/session-cache/session-manager.js

https://eaflood.atlassian.net/browse/IWTF-2139
The footer links are broken on the order complete and payment failed page

Footer links broken on some pages

---

packages/gafl-webapp-service/src/processors/__tests__/analytics.spec.js
packages/gafl-webapp-service/src/processors/analytics.js

Fix: Handles new and old GA Client id formats

---

packages/gafl-webapp-service/src/pages/contact/address/select/address-select.njk

Fix: Adds visually hidden text to Change link on address-select page

---

packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
packages/gafl-webapp-service/src/session-cache/session-manager.js

https://eaflood.atlassian.net/browse/IWTF-1877
Cannot navigate directly to easy renewal page

Cannot navigate directly to easy renewal page

---

packages/gafl-webapp-service/src/pages/contact/address/select/address-select.njk
packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk

IWTF-2149
* Updates visually hidden text to lowercase

Fix: Updates visually hidden text to correct case

---

packages/gafl-webapp-service/src/pages/layout/layout.njk

Fix: Adds visually hidden text to cookie banner close button

---

packages/gafl-webapp-service/src/pages/guidance/privacy-policy.njk

IWTF-2154
*Updates content
*Fixes headings

Content-changes: Updates Privacy Policy

---

packages/connectors-lib/package-lock.json
packages/connectors-lib/package.json

https://eaflood.atlassian.net/browse/IWTF-2068
Revert bump of airbrake/node in connectors-lib as it is causing problems for fulfilment job. I do not know why.

Fix broken fulfilment job

---

packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/licence-fulfilment.njk
packages/gafl-webapp-service/src/pages/order-complete/licence-information/licence-information.njk
packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk
packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js

https://eaflood.atlassian.net/browse/IWTF-2199
Amendments to the payment complete screen following QA

Amendments to the payment complete screen following QA

---

packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk

Content: Update accessibility statement

---

packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/licence-fulfilment.njk
packages/gafl-webapp-service/src/pages/order-complete/licence-information/licence-information.njk

https://eaflood.atlassian.net/browse/IWTF-2219
Consistent and secure page title for the HTML licence details

Consistent and secure page title for the HTML licence details

---

packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
packages/gafl-webapp-service/src/uri.js

https://eaflood.atlassian.net/browse/IWTF-2265
pdf licences downloading with the incorrect file type

pdf licences downloading with the incorrect file type

---

.github/workflows/build.yml

https://eaflood.atlassian.net/browse/IWTF-2224
Changelog generation has been broken for a while. This is an attempt to
fix it...

Fix changelog generation

---

packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
packages/gafl-webapp-service/src/pages/errors/server-error.njk
packages/gafl-webapp-service/src/pages/guidance/os-terms.njk
packages/gafl-webapp-service/src/pages/layout/layout.njk

https://eaflood.atlassian.net/browse/IWTF-2209
Links opening in new window without notifying the user

Links opening in new window without notifying the user

---

packages/gafl-webapp-service/src/pages/errors/server-error.njk

https://eaflood.atlassian.net/browse/IWTF-2316
Feedback link broken on error page

Feedback link broken on error page

---

packages/gafl-webapp-service/src/pages/guidance/privacy-policy.njk

Content: Updates privacy policy

---

packages/sales-api-service/src/server/routes/__tests__/staging-exceptions.spec.js
packages/sales-api-service/src/server/routes/staging-exceptions.js

Bugfix: Updates isDataValidation check

---

packages/business-rules-lib/src/validators/__tests__/contact.validators.spec.js
packages/business-rules-lib/src/validators/contact.validators.js

https://eaflood.atlassian.net/browse/IWTF-2315
Prevent 2 digit years for date of birth from being accepted

Unexpected response from the Sales API - date before minimum allowed

---

packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
packages/gafl-webapp-service/src/handlers/page-handler.js

https://eaflood.atlassian.net/browse/IWTF-2312
An error is being thrown in live, need additional logging to find out why

Cannot read property 'order-complete' of undefined

---

packages/gafl-webapp-service/src/pages/guidance/cookies.njk

https://eaflood.atlassian.net/browse/IWTF-2327
Update duration of cookies

Update cookie statement

---

packages/gafl-webapp-service/src/pages/layout/layout.njk

https://eaflood.atlassian.net/browse/IWTF-2294
Removal of Beta badge on GAFL service

Removal of Beta badge on GAFL service

---

packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk

Content Changes: Removes references to PDF in accessibility statement

---

packages/dynamics-lib/src/entities/__tests__/__snapshots__/pocl-validaton-error.entity.spec.js.snap
packages/dynamics-lib/src/entities/__tests__/pocl-validaton-error.entity.spec.js
packages/pocl-job/src/staging/__tests__/__snapshots__/pocl-validation-errors.spec.js.snap
packages/pocl-job/src/staging/__tests__/pocl-validation-errors.spec.js
packages/pocl-job/src/staging/pocl-validation-errors.js
packages/sales-api-service/src/schema/staging-exception.schema.js
packages/sales-api-service/src/server/routes/staging-exceptions.js
packages/sales-api-service/src/services/exceptions/__tests__/__snapshots__/pocl-validation-errors.service.spec.js.snap
packages/sales-api-service/src/services/exceptions/__tests__/pocl-validation-errors.service.spec.js

Fix: Sonar cloud issues & test coverage

---

packages/dynamics-lib/src/queries/__tests__/concession-proof.queries.spec.js
packages/dynamics-lib/src/queries/concession-proof.queries.js
packages/sales-api-service/src/server/routes/__tests__/authenticate.spec.js

https://eaflood.atlassian.net/browse/IWTF-2343
Easy renewals login not working - add additional test and default filter

Easy renewals login not working - clean up

---

packages/connectors-lib/src/__tests__/airbrake.spec.js
packages/connectors-lib/src/airbrake.js
packages/gafl-webapp-service/src/handlers/error-handler.js

https://eaflood.atlassian.net/browse/IWTF-2367
Add more logging details to errbit

Add more logging details to errbit

---

packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk

https://eaflood.atlassian.net/browse/IWTF-2361
Update content on payment confirmation screen

Update content on payment confirmation screen

---

packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk

https://eaflood.atlassian.net/browse/IWTF-2361
Fixed issue when the licence is make a note

Fixed issue when the licence is make a note

---

packages/gafl-webapp-service/src/__tests__/server-ga-integration.spec.js
packages/gafl-webapp-service/src/constants.js
packages/gafl-webapp-service/src/pages/contact/address/entry/result-function.js
packages/gafl-webapp-service/src/pages/contact/address/select/result-function.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/result-function.js
packages/gafl-webapp-service/src/processors/__tests__/renewals-write-cache.spec.js
packages/gafl-webapp-service/src/processors/renewals-write-cache.js
packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-1980
Implement digital licence flow into easy renewals journey

Implement digital licence flow into easy renewals journey

---

packages/gafl-webapp-service/src/handlers/agreed-handler.js
packages/gafl-webapp-service/src/processors/__tests__/permission-helper.spec.js
packages/gafl-webapp-service/src/processors/api-transaction.js
packages/gafl-webapp-service/src/processors/permission-helper.js

Add page, transaction and status cache when permission start date is before issue date / current date

Additional logging for start date before issue date problem

---

packages/gafl-webapp-service/src/session-cache/add-permission.js

https://eaflood.atlassian.net/browse/IWTF-2378
Additional logging for order-complete undefined

Additional logging for order-complete undefined

---

packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/concessions/date-of-birth/update-transaction.js

Adds error logging when page cache does not match payload

---

packages/dynamics-lib/src/entities/pocl-validation-error.entity.js
packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/concessions/date-of-birth/update-transaction.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
packages/gafl-webapp-service/src/pages/terms-and-conditions/route.js
packages/gafl-webapp-service/src/processors/__tests__/payment.spec.js
packages/gafl-webapp-service/src/session-cache/session-manager.js

https://eaflood.atlassian.net/browse/IWTF-2353
Fix failing sonar checks for rod-licensing

Fix failing sonar checks for rod-licensing

---

packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
packages/gafl-webapp-service/src/pages/renewals/identify/route.js
packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
packages/gafl-webapp-service/src/session-cache/session-manager.js

https://eaflood.atlassian.net/browse/IWTF-2451
Unexpected error is displayed when try to renew another license

Unexpected error is displayed when try to renew another license

---

packages/gafl-webapp-service/src/pages/contact/digital-licence/check-confirmation-contact/__tests__/__snapshots__/check-confirmation-contact.spec.js.snap
packages/gafl-webapp-service/src/pages/contact/digital-licence/check-confirmation-contact/__tests__/check-confirmation-contact.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/check-confirmation-contact/check-confirmation-contact.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/check-confirmation-contact/route.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/__snapshots__/licence-confirmation-method.spec.js.snap
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/licence-confirmation-method.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/licence-confirmation-method.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/route.js
packages/gafl-webapp-service/src/routes/journey-definition.js
packages/gafl-webapp-service/src/routes/routes.js
packages/gafl-webapp-service/src/uri.js

IWTF-2412
* Adds check confirmation contact route and page
* Updates licence confirmation method page

Adds email/text check page

---

packages/gafl-webapp-service/src/__tests__/server-ga-integration.spec.js
packages/gafl-webapp-service/src/constants.js
packages/gafl-webapp-service/src/pages/contact/address/entry/result-function.js
packages/gafl-webapp-service/src/pages/contact/address/select/result-function.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/result-function.js
packages/gafl-webapp-service/src/processors/__tests__/renewals-write-cache.spec.js
packages/gafl-webapp-service/src/processors/renewals-write-cache.js
packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-2452
Fix issue when navigating back on easy renewals

Fix issue when navigating back on easy renewals

---

packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk
packages/gafl-webapp-service/src/pages/renewals/identify/route.js

https://eaflood.atlassian.net/browse/IWTF-2436
Link to redirect to buy on renewal page

Link to redirect to buy on renewal page

---

packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk

https://eaflood.atlassian.net/browse/IWTF-2436
Added missing class to link

Added missing class to link

---

scripts/github/deploy.sh

As of October 4th, NPM disallowed HTTP traffic: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/.
Therefore, we need to switch to HTTPS

fix version script

---

packages/gafl-webapp-service/src/pages/contact/name/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/contact/name/name.njk
packages/gafl-webapp-service/src/pages/contact/name/route.js
packages/gafl-webapp-service/src/routes/__tests__/back-links.spec.js
packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-2381
As a Angler, I want the ability to enter the name of the individual I opted to purchase the licence for. So that I can provide mine or someone else's First and Last name.

What is your name?

---

packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk

https://eaflood.atlassian.net/browse/IWTF-1776
Annual accessibility statement review - Summer 2021

Annual accessibility statement review - Summer 2021

---

packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/licence-fulfilment.njk

https://eaflood.atlassian.net/browse/IWTF-2536
Incorrect wording on the rod licence paperless web journey

Incorrect wording on the rod licence paperless web journey

---

packages/gafl-webapp-service/src/pages/concessions/date-of-birth/route.js
packages/gafl-webapp-service/src/pages/concessions/disability/__tests__/disability-concession.spec.js
packages/gafl-webapp-service/src/pages/concessions/disability/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/concessions/disability/disability-concession.njk
packages/gafl-webapp-service/src/pages/concessions/disability/route.js
packages/gafl-webapp-service/src/pages/contact/name/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/contact/name/route.js
packages/gafl-webapp-service/src/processors/__tests__/licence-type-display.spec.js
packages/gafl-webapp-service/src/processors/licence-type-display.js
packages/gafl-webapp-service/src/routes/__tests__/back-links.spec.js
packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-2383
As a Angler, I want to be able to provide any concessions I am eligible for, prior to determining when a licence starts

Do you receive any of the following?

---

packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk
packages/gafl-webapp-service/src/pages/licence-details/licence-for/licence-for.njk
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/licence-to-start.spec.js
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/route.js
packages/gafl-webapp-service/src/routes/__tests__/back-links.spec.js
packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-2384
As an Angler, I want to be able to determine licence start date, after I have declared eligible concessions. So that I can get the best value from the licence.

When would you like your licence to start?

---

packages/gafl-webapp-service/src/pages/concessions/disability/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/licence-details/licence-type/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/licence-details/licence-type/licence-type.njk
packages/gafl-webapp-service/src/pages/licence-details/licence-type/route.js

https://eaflood.atlassian.net/browse/IWTF-2521
As a Angler, I want to be able to determine the type of licence I want to purchase, so that I can select the correct licence

Licence Type

---

packages/gafl-webapp-service/src/pages/licence-details/licence-length/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/licence-details/licence-length/licence-length.njk
packages/gafl-webapp-service/src/pages/licence-details/licence-length/route.js

https://eaflood.atlassian.net/browse/IWTF-2521
As a Angler,  I want to be able to determine the type of licence I want to purchase , so that I can select the correct licence

Licence Type Multibuy

---

packages/gafl-webapp-service/assets/sass/main.scss
packages/gafl-webapp-service/assets/sass/rod-licensing/_table_extras.scss
packages/gafl-webapp-service/src/pages/contact/name/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/contact/name/result-function.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-2577
As a Angler, I want to be able to view the licence details, so that I can verify the details and change any of the licence details if I have made an error

Check the licence details

---

packages/gafl-webapp-service/src/pages/contact/address/lookup/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
packages/gafl-webapp-service/src/pages/contact/address/lookup/route.js

https://eaflood.atlassian.net/browse/IWTF-2578
As a Angler, I want the ability to find an address, so that I can select the address I wish the licence to be sent to

Find your address multibuy

---

packages/gafl-webapp-service/src/handlers/__tests__/error-handler.spec.js
packages/gafl-webapp-service/src/handlers/error-handler.js
packages/gafl-webapp-service/src/pages/errors/client-error.njk

https://eaflood.atlassian.net/browse/IWTF-2524
This work is to improve the error screen so that it's possible to go
back to the step you were on previously.

Generic Notice of Service Error

---

packages/gafl-webapp-service/src/pages/terms-and-conditions/terms-and-conditions.njk

https://eaflood.atlassian.net/browse/IWTF-2584
Previous content: I agree to the terms and conditions
New content: I agree to the licence conditions

Update Licence conditions screen

---

packages/gafl-webapp-service/src/pages/contact/contact/contact.njk

https://eaflood.atlassian.net/browse/IWTF-2545
As an Angler purchasing a 12 Month Licence, I want to the content updated on the ‘How should we contact you?’ page, so that the information is clearer

Content update: How should we contact you? Screen

---

packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/licence-fulfilment.njk

https://eaflood.atlassian.net/browse/IWTF-2597
Content update for paperless screen

Do you want to go paperless?

---

packages/gafl-webapp-service/src/pages/contact/contact/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
packages/gafl-webapp-service/src/pages/contact/contact/route.js

https://eaflood.atlassian.net/browse/IWTF-2599
Wording changes for the contact screen

BOBO: How should we contact you

---

packages/gafl-webapp-service/src/__mocks__/mock-journeys.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions.spec.js

https://eaflood.atlassian.net/browse/IWTF-2601
As an Angler I want the ability to check the contact details I have entered, so that I can ensure the data I have inputted is correct

Check contact details

---

packages/gafl-webapp-service/src/pages/concessions/disability/disability-concession.njk

https://eaflood.atlassian.net/browse/IWTF-2592

update error message on disability concession

---

packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/licence-fulfilment.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/route.js

https://eaflood.atlassian.net/browse/IWTF-2634
Do you want to go paperless header

Do you want to go paperless header

---

packages/gafl-webapp-service/src/pages/contact/contact/contact.njk

https://eaflood.atlassian.net/browse/IWTF-2592

updated error message for email

---

packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/terms-and-conditions/route.js
packages/gafl-webapp-service/src/uri.js

https://eaflood.atlassian.net/browse/IWTF-2642
I want the URL of the licence conditions page to be amended to remove reference to terms and leave just conditions

Update licence confirmation page URL

---

packages/gafl-webapp-service/src/pages/concessions/disability/disability-concession.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/check-confirmation-contact/check-confirmation-contact.njk
packages/gafl-webapp-service/src/pages/licence-details/licence-type/licence-type.njk
packages/gafl-webapp-service/src/pages/macros/pricing-summary.njk
packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk

https://eaflood.atlassian.net/browse/IWTF-2625
Update content for BOBO journey screens that are already developed

Update content for BOBO journey screens that are already developed

---

docker/README.md

https://eaflood.atlassian.net/browse/IWTF-2663?atlOrigin=eyJpIjoiMjRlOGNhYmM3MWFjNGFhNTg0MTQwYTdkNWFjYzY4ZTMiLCJwIjoiaiJ9
Updating readme to fix error in renaming files

Update readme for env var structure

---

packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
packages/gafl-webapp-service/src/handlers/attribution-handler.js

Redirect from attribution to renewals doesn't work, this is to fix it

Fix attribution redirect for renewals

---

packages/fulfilment-job/package-lock.json
packages/fulfilment-job/package.json
packages/fulfilment-job/src/staging/__tests__/deliver-fulfilment-files.spec.js
packages/fulfilment-job/src/staging/deliver-fulfilment-files.js

https://eaflood.atlassian.net/browse/IWTF-2196
Upgrade OpenPGP Library to release version for latest version (v5), as we're on a prerelease version

Upgrade OpenPGP Library

---

packages/gafl-webapp-service/src/handlers/__tests__/url-handler.spec.js
packages/gafl-webapp-service/src/handlers/url-handler.js
packages/gafl-webapp-service/src/uri.js

https://eaflood.atlassian.net/browse/IWTF-2720?atlOrigin=eyJpIjoiMGQ1ZGVhNmZkYjE0NDdiODhlN2UxMTc3MmQzN2UyODAiLCJwIjoiaiJ9
updating to a friendly 'vanity' url for easy renewals attribution

Easy renewals vanity URL

---

package-lock.json
package.json

https://eaflood.atlassian.net/browse/IWTF-2741
Update prettier dependency

Update prettier dependency

---

packages/connectors-lib/package-lock.json
packages/connectors-lib/package.json
packages/fulfilment-job/src/fulfilment-processor.js

After the first attempt of the upgrade didn't work correctly here, https://github.com/DEFRA/rod-licensing/commit/bf18f566026b850c90d9d7376aefa33ae0e3002e this ticket is the second attempt

Upgrade airbrake 2

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk

https://eaflood.atlassian.net/browse/IWTF-2160
Fixing accessibility issues with date picker not showing text

Alternate image text for calendar

---

packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/concessions/date-of-birth/update-transaction.js

https://eaflood.atlassian.net/browse/IWTF-2422
Removing additonal logs that were included to help with fixing bug

Remove additional logging

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json

https://eaflood.atlassian.net/browse/IWTF-2749
'Where should we send the fishing licence' text will be updated when buying for someone else (paperless)

Bobo journey update where send licence text

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json

https://eaflood.atlassian.net/browse/IWTF-2778
Check contact pager has a link that requires updating with generic text.

Update to licence details link to be more generic

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json

https://eaflood.atlassian.net/browse/IWTF-2796
Update to the find address hints so they look more consistent.

Update find address hint text to be consistent

---

docker/README.md

https://eaflood.atlassian.net/browse/IWTF-2754
Update readme with Docker Desktop upgrade instructions

Update readme with Docker Desktop upgrade instructions

---

docker/README.md

https://eaflood.atlassian.net/browse/IWTF-2847
Update documentation on volumes

Update documentation on volumes

---

package-lock.json
package.json
packages/connectors-lib/src/__mocks__/aws-sdk.js
packages/fulfilment-job/src/__mocks__/aws-sdk.js
packages/pocl-job/src/__mocks__/aws-sdk.js
packages/sales-api-service/src/__mocks__/aws-sdk.js
packages/sqs-receiver-service/src/__mocks__/aws-sdk.js

https://eaflood.atlassian.net/browse/IWTF-2746
Remove aws-sdk dependency from main package.json

Remove aws-sdk dependency from main package.json

---

packages/gafl-webapp-service/src/__tests__/server.spec.js
packages/gafl-webapp-service/src/pages/layout/layout.njk
packages/gafl-webapp-service/src/server.js

https://eaflood.atlassian.net/browse/IWTF-2782
Welsh Language toggle

Welsh Language toggle 

---

packages/gafl-webapp-service/src/locales/en.json

https://eaflood.atlassian.net/browse/IWTF-2813
Rewording how we should contact the licence holder about reminders and important changes

BOBO - wording how contact

---

packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/licence-confirmation-method.njk

https://eaflood.atlassian.net/browse/IWTF-2809
Rewording of page for where should send the fish licence for bobo

Bobo - where send licence

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2807
Minor updates are required to welsh lang on licence start page.

Minor updates to the 'When would you like your licence to start? '

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2808
Update do you recieve any of the following page to welsh with added translation for title and fix error message translation

Welsh translate - Do you receive any of the following?

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2825
Update welsh translation to bobo licence-type page.

Update welsh lang bobo licence type

---

packages/sales-api-service/src/schema/staging-exception.schema.js
packages/sales-api-service/src/server/routes/__tests__/staging-exceptions.spec.js

https://eaflood.atlassian.net/browse/IWTF-2832
Validation errors not handled for DD File

Validation errors not handled for DD File

---

packages/pocl-job/src/transform/bindings/pocl/transaction/__tests__/__snapshots__/transaction.bindings.spec.js.snap
packages/pocl-job/src/transform/bindings/pocl/transaction/__tests__/transaction.bindings.spec.js
packages/pocl-job/src/transform/bindings/pocl/transaction/transaction.bindings.js

https://eaflood.atlassian.net/browse/IWTF-2833
When importing a DD file, the system date and time are seemingly used to set both the issue date and the start date, the start date in the file seems to be ignored.

DD Import start date & time

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2829
Added translation for Choose their address

Added translation for Choose their address

---

packages/gafl-webapp-service/src/routes/__tests__/misc-routes-cookies.spec.js
packages/gafl-webapp-service/src/routes/misc-routes.js

https://eaflood.atlassian.net/browse/IWTF-2885
Fix for cookies page missing cookie names, also add tests so it won't happen again

Cookies page missing cookie names

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2822
DOB translation for error message differs to expected.

Bug fix for BOBO date of birth page

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json

https://eaflood.atlassian.net/browse/IWTF-2868
Updating the example address hint to be all lower case

Update address hints to lower case

---

packages/gafl-webapp-service/src/pages/terms-and-conditions/terms-and-conditions.njk

https://eaflood.atlassian.net/browse/IWTF-2866
Amend placement of warning on Licence conditions page

Amend placement of warning on Licence conditions page

---

packages/business-rules-lib/src/validators/__tests__/contact.validators.spec.js
packages/business-rules-lib/src/validators/contact.validators.js
packages/gafl-webapp-service/src/pages/renewals/identify/route.js

https://eaflood.atlassian.net/browse/IWTF-2838
Update validation for postcodes to be able to accept international. Only leave so maximum 12 characters

International postcodes not accepted

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2828
Update welsh translation for BOBO manual address entry page.

Welsh lang update for BOBO man address entry page

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2831
Update welsh lang for the BOBO how should we contact them page.

Welsh lang update BOBO how should we contact them page

---

packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk

https://eaflood.atlassian.net/browse/IWTF-2896
Fix for the birthdate entry screen always failing validation when language is set to Welsh

Birthdate validation fails in Welsh

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2713
Is the phone number correct - welsh translation

Is the phone number correct - welsh translation

---

packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk

https://eaflood.atlassian.net/browse/IWTF-2869
Page title does not resemble the find address page

Page title does not resemble the find address page

---

packages/gafl-webapp-service/package-lock.json
packages/sales-api-service/package-lock.json

Update critical dependencies
https://eaflood.atlassian.net/browse/IWTF-2907
Update dependencies with critical updates due: minimise from v1.2.5 to v1.2.6

Version updates

---

packages/gafl-webapp-service/src/handlers/__tests__/multibuy-for-you-handler.spec.js
packages/gafl-webapp-service/src/handlers/multibuy-for-you-handler.js
packages/gafl-webapp-service/src/handlers/result-functions.js
packages/gafl-webapp-service/src/handlers/update-transaction-functions.js
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/result-function.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js

https://eaflood.atlassian.net/browse/IWTF-2771
When multibuy they save basic input details so dont have to put in same data again

Multibuy - saving input details

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2826
Updating welsh translation on the bobo journey on 'How long do they want the licence for?' page

Welsh - BOBO how long do they want licence for

---

packages/gafl-webapp-service/src/pages/renewals/renewal-inactive/__tests__/route.spec.js

https://eaflood.atlassian.net/browse/IWTF-2906
Fix failing test on short licence error page update

Fix failing test on short licence error page update 

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2729
Update 'How should we contact you with reminders and important changes?' with welsh

Welsh - how contact with reminders

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2738
This change updates the title attribute to match the page heading.

Update Welsh language title attribute for refund policy

---

packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/pages/layout/layout.njk

https://eaflood.atlassian.net/browse/IWTF-2850
This link should open in a new tab, and say that it opens in a new tab.

Open OS terms footer link in a new tab

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2911
Update who is licence for page following NRW comments

Welsh - NRW comments on who licence for

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2690
Update BOBO - How do they want their fishing licence confirmation? with welsh

Welsh - bobo fishing licence confirmation

---

packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-2908
Fix issue with when navigating to find your address, then back to licence for an error is thrown

Error when navigating to licence for from find your address

---

packages/gafl-webapp-service/src/handlers/new-session-handler.js
packages/gafl-webapp-service/src/routes/__tests__/misc-routes.spec.js
packages/gafl-webapp-service/src/routes/misc-routes.js

https://eaflood.atlassian.net/browse/IWTF-2898
Update misc route handler to be able to persist language

Persist language in misc route

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2914
Update find their address heading to include welsh for bobo journey

Welsh - find their address heading

---

packages/dynamics-lib/src/entities/__tests__/__snapshots__/permission.entity.spec.js.snap
packages/dynamics-lib/src/entities/__tests__/permission.entity.spec.js
packages/dynamics-lib/src/entities/permission.entity.js
packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
packages/sales-api-service/src/services/transactions/process-transaction-queue.js

https://eaflood.atlassian.net/browse/IWTF-2928
Add a flag to identify multibuy licences

Identify multibuy licences

---

packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/licence-confirmation-method.njk

https://eaflood.atlassian.net/browse/IWTF-2910
Display correct error message when input phone number incorrect

Accessibility - Phone error message

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2939
Update the title on enter address manually for welsh language

Welsh - Enter address manual title

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-2993
Add welsh translation for easy renewals check licence details page.

feature/iwtf 2993 Easy renewals check licence details welsh translation

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-3024
Minor copy change to the heading on the 'Which type of licence do you want?' page. From 'Pa fath o drwydded sydd gennych mewn golwg?' to 'Pa fath o drwydded hoffech chi ei chael?'

Welsh translation update to licence type page title

---

package-lock.json
package.json
packages/gafl-webapp-service/src/handlers/multibuy-for-you-handler.js
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/result-function.js
packages/gafl-webapp-service/src/pages/multibuy/change-licence-options/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/multibuy/change-licence-options/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/multibuy/change-licence-options/route.js
packages/gafl-webapp-service/src/pages/multibuy/view-licences/route.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
packages/gafl-webapp-service/src/processors/__tests__/licence-type-display.spec.js
packages/gafl-webapp-service/src/processors/licence-type-display.js
packages/sales-api-service/package-lock.json

https://eaflood.atlassian.net/browse/IWTF-3028
Fixing the two code smells and broken tests on the multibuy branch

Fix code smells and broken tests on multibuy branch

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-3034
This PR makes a requested change to a paragraph on the "find your address" page.

Amend Welsh translation on address lookup page

---

packages/gafl-webapp-service/src/plugins.js

Update to allow the env variable to be able to notice if analytics tracked

Log tracking analytics

---

packages/gafl-webapp-service/src/pages/contact/contact/contact.njk

https://eaflood.atlassian.net/browse/IWTF-2984
Accessibility issue with the phone number error message on Contact page

Accessibility - phone number on contact

---

packages/gafl-webapp-service/src/pages/order-complete/licence-details/__tests__/licence-details.spec.js
packages/gafl-webapp-service/src/pages/order-complete/licence-details/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
packages/gafl-webapp-service/src/processors/__tests__/date-and-time-display.spec.js
packages/gafl-webapp-service/src/processors/date-and-time-display.js

https://eaflood.atlassian.net/browse/IWTF-3020
Update welsh language for the month on the licence start field and date of birth field on the licence summary page.

Update welsh language of months on licence summary page

---

packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/multibuy/view-licences/route.js

https://eaflood.atlassian.net/browse/IWTF-3063
Update to allow mssgs to have value when trying load licences page for multibuy

Multibuy - unable view multiple licences

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/pages/multibuy/view-licences/view-licences.njk

https://eaflood.atlassian.net/browse/IWTF-3003
Update title on selected licences page

Accessibility - Selected licences title

---

packages/gafl-webapp-service/src/handlers/__tests__/__snapshots__/page-handler.spec.js.snap
packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
packages/gafl-webapp-service/src/handlers/page-handler.js
packages/gafl-webapp-service/src/pages/layout/layout.njk

https://eaflood.atlassian.net/browse/IWTF-3075
Only display analytics banner when uri begins with /buy

analytics banner only /buy

---

packages/gafl-webapp-service/src/handlers/__tests__/analytics-handler.spec.js
packages/gafl-webapp-service/src/handlers/analytics-handler.js

https://eaflood.atlassian.net/browse/IWTF-3073
Change redirect so for renewal it doesnt redirect to main journey

Cannot accept/reject analytics on renewal

---

packages/gafl-webapp-service/src/handlers/__tests__/analytics-handler.spec.js
packages/gafl-webapp-service/src/handlers/analytics-handler.js

https://eaflood.atlassian.net/browse/IWTF-3085
Whether accept or reject is pressed on the analytics banner, an error is thrown in pre-prod

Actioning analytics banner throws an error

---

packages/gafl-webapp-service/src/pages/multibuy/view-licences/view-licences.njk

https://eaflood.atlassian.net/browse/IWTF-3005
Changing screen reader to read change instead of main land

Screen reader change button

---

packages/gafl-webapp-service/src/routes/__tests__/__snapshots__/error-routes.spec.js.snap
packages/gafl-webapp-service/src/routes/__tests__/error-routes.spec.js
packages/gafl-webapp-service/src/routes/error-routes.js

https://eaflood.atlassian.net/browse/IWTF-3049
Page so when /server-error displays the server error page

Route to view server error page

---

packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
packages/gafl-webapp-service/src/handlers/page-handler.js

https://eaflood.atlassian.net/browse/IWTF-3109
User should be able to click the back button and go back to relevant page, at present it throws a 500 error.

Fix for back link button

---

packages/gafl-webapp-service/gafl-jest-matchers.js
packages/gafl-webapp-service/package.json
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js

When doing a merge from develop, this functionality was almost deleted due to it being entirely untested. Uncommenting this functionality and adding tests for it.

Multibuy - copy input details

---

packages/gafl-webapp-service/gafl-jest-matchers.js
packages/gafl-webapp-service/package.json

Adding the new GetDataRedirect matcher for GAFL that's already been committed to the multibuy branch

Add new custom matcher for GAFL

---

packages/gafl-webapp-service/src/handlers/__tests__/analytics-handler.spec.js
packages/gafl-webapp-service/src/handlers/analytics-handler.js

https://eaflood.atlassian.net/browse/IWTF-3105
Error message dispalying when in welsh and try to select analytics

Analytics error when in welsh

---

packages/gafl-webapp-service/src/pages/licence-details/no-licence-required/no-licence-required.njk

https://eaflood.atlassian.net/browse/IWTF-3038
Amend so delete "how much will this cost" from journey when under 13 journey

Amend journey content for under 13

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-3132
User should be able to read page in Welsh with correct translations.

Translation to how do they want their licence page

---

packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js

https://eaflood.atlassian.net/browse/IWTF-3099
Refactor licence summary page, bringing licence summary rows out of the nunjucks template and into the getData function so that they can be tested

Refactor licence summary page

---

packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js

https://eaflood.atlassian.net/browse/IWTF-3152
Persist language choice between order complete and Licence details page

Persist language - order complete and licence details

---

docker/infrastructure.yml
docker/resources/infrastructure/localstack/localstack-cfn.yml

Update the dev env docker config to work with the new M1 Macbook

Update dev env docker config

---

packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js

In the last merge from develop, a few gaps in code coverage were highlighted. This PR addresses these gaps.

Improve coverage

---

packages/gafl-webapp-service/src/pages/terms-and-conditions/terms-and-conditions.njk

https://eaflood.atlassian.net/browse/IWTF-3149
Change location of back button to above pay for the licence button

Back button during payment

---

packages/gafl-webapp-service/src/session-cache/__tests__/cache-decorator.spec.js
packages/gafl-webapp-service/src/session-cache/cache-decorator.js

https://eaflood.atlassian.net/browse/IWTF-2942
This error mostly seems to occur when pressing back from GovPay.
Although the cause isn't too clear, the fix looks to be straightforward
so this is to fix it

Fix cache error

---

packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-3211
Change in journey definition to allow go licence conditions

Navigate to licence conditions page

---

packages/gafl-webapp-service/src/pages/terms-and-conditions/terms-and-conditions.njk
packages/gafl-webapp-service/src/routes/__tests__/back-links.spec.js

https://eaflood.atlassian.net/browse/IWTF-3207
Message not to press back moved to top of page for multibuy

Do not push back after payment - multibuy

---

packages/gafl-webapp-service/src/routes/journey-definition.js

https://eaflood.atlassian.net/browse/IWTF-3211
Change link from add licence in journey definition to go to t&c page, change back link to match

Show licence conditions page

---

packages/gafl-webapp-service/src/pages/order-complete/licence-details/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/order-complete/licence-details/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/order-complete/licence-details/route.js

https://eaflood.atlassian.net/browse/IWTF-3007
Display the correct length for all licences displayed

List multiple licences on information page

---

packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
packages/gafl-webapp-service/src/handlers/page-handler.js

https://eaflood.atlassian.net/browse/IWTF-2325
Remove logging for cannot read property 'order complete'

Remove 'order-complete' undefined logging

---

docker/env/gafl_webapp.env.example
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/route.js
packages/gafl-webapp-service/src/pages/macros/notification-banner.njk
packages/gafl-webapp-service/src/pages/macros/standard-form.njk
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js

https://eaflood.atlassian.net/browse/IWTF-3179
Implement notification banner - in this occurence for price changes

Notification banner

---

packages/business-rules-lib/src/index.js
packages/business-rules-lib/src/util/__tests__/permissions.spec.js
packages/business-rules-lib/src/util/permissions.js
packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk
packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
packages/sales-api-service/src/services/transactions/create-transaction.js

https://eaflood.atlassian.net/browse/IWTF-3185
Use the permit associated with the permission to calculate the price, rather than cost being a static value

Add getPrice to Permission

---

packages/gafl-webapp-service/src/pages/licence-details/licence-type/__tests__/licence-type.spec.js
packages/gafl-webapp-service/src/processors/__tests__/__snapshots__/pricing-summary.spec.js.snap
packages/gafl-webapp-service/src/processors/__tests__/pricing-summary.spec.js
packages/gafl-webapp-service/src/processors/pricing-summary.js

https://eaflood.atlassian.net/browse/IWTF-3268
Update pricingDetail to return strings and pad decimals to two places where necessary

On licence type page, prices should display with two decimals or none

---

packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
packages/gafl-webapp-service/src/processors/__tests__/price-display.spec.js
packages/gafl-webapp-service/src/processors/price-display.js

https://eaflood.atlassian.net/browse/IWTF-3273
The price shown is the old price.

Price incorrect on Licence Summary page

---

packages/business-rules-lib/src/util/__tests__/ages.spec.js
packages/business-rules-lib/src/util/ages.js
packages/gafl-webapp-service/src/processors/__tests__/concession-helper-spec.js
packages/gafl-webapp-service/src/processors/concession-helper.js
packages/sales-api-service/src/services/__tests__/permissions.service.spec.js
packages/sales-api-service/src/services/permissions.service.js

https://eaflood.atlassian.net/browse/IWTF-3188
Changes to raise the age of senior concession from 65 to 66

Change in age of senior concession

---

packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk
packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js

https://eaflood.atlassian.net/browse/IWTF-3283
We recently changed how the displayed price was calculated, but this led to some unintended behaviour on the completion page where the word "free" was displayed with the header. This change fixes that.

Fix completion message for junior licences

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json

Add this suffix to be consistent with other guidance pages

Add "GOV.UK" suffix to new prices page title

---

packages/gafl-webapp-service/src/handlers/result-functions.js
packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/contact/address/entry/result-function.js
packages/gafl-webapp-service/src/pages/contact/address/select/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/contact/address/select/result-function.js
packages/gafl-webapp-service/src/pages/contact/contact/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/contact/contact/result-function.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/result-function.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/result-function.js
packages/gafl-webapp-service/src/pages/contact/newsletter/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/contact/newsletter/result-function.js

https://eaflood.atlassian.net/browse/IWTF-3208
After updating preferences and pressing continue I am redirected back to the change contact details page

Contact pages routes

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-3267
remove additional full stop

Welsh - date of birth page

---

packages/gafl-webapp-service/src/handlers/__tests__/analytics-handler.spec.js
packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
packages/gafl-webapp-service/src/handlers/analytics-handler.js
packages/gafl-webapp-service/src/pages/contact/contact/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/licence-details/licence-length/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/processors/__tests__/api-transaction.spec.js
packages/gafl-webapp-service/src/routes/__tests__/error-routes.spec.js
packages/pocl-job/src/io/__tests__/s3.spec.js

https://eaflood.atlassian.net/browse/IWTF-2924
This PR covers adding additional tests to fill the gaps in our unit test coverage.

Improve test coverage

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json

https://eaflood.atlassian.net/browse/IWTF-3191
change title of page to match prototype

multibuy delete licence page

---

packages/gafl-webapp-service/src/routes/__tests__/__snapshots__/error-routes.spec.js.snap
packages/gafl-webapp-service/src/routes/__tests__/error-routes.spec.js
packages/gafl-webapp-service/src/routes/error-routes.js

https://eaflood.atlassian.net/browse/IWTF-3328
Add code to allow welsh language to persist when click start again on client error page

Error page persist welsh

---

packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/multibuy/view-licences/route.js
packages/gafl-webapp-service/src/pages/multibuy/view-licences/view-licences.njk

https://eaflood.atlassian.net/browse/IWTF-3272
When licences remaining change link to go to add licence page

Licence basket link

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-3294
Add full stop that is missing from welsh content

Welsh language refund policy

---

packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/multibuy/view-licences/route.js
packages/gafl-webapp-service/src/pages/multibuy/view-licences/view-licences.njk

https://eaflood.atlassian.net/browse/IWTF-3376
Once removed all licences and start journey clear cache

Clear cache when no licences left

---

packages/business-rules-lib/src/util/__tests__/ages.spec.js
packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
packages/gafl-webapp-service/src/processors/__tests__/licence-type-display.spec.js
packages/sales-api-service/src/services/__tests__/permissions.service.spec.js

Further PR with more thorough cleanup to follow pending Jira ticket.

Fix tests expecting 65 to still be senior concession age

---

lerna.json
packages/business-rules-lib/package-lock.json
packages/business-rules-lib/package.json
packages/connectors-lib/package-lock.json
packages/connectors-lib/package.json
packages/dynamics-lib/package-lock.json
packages/dynamics-lib/package.json
packages/fulfilment-job/package-lock.json
packages/fulfilment-job/package.json
packages/gafl-webapp-service/package-lock.json
packages/gafl-webapp-service/package.json
packages/payment-mop-up-job/package-lock.json
packages/payment-mop-up-job/package.json
packages/pocl-job/package-lock.json
packages/pocl-job/package.json
packages/sales-api-service/package-lock.json
packages/sales-api-service/package.json
packages/sqs-receiver-service/package-lock.json
packages/sqs-receiver-service/package.json

Update versions for different packages so able to release

Package Versions

---

packages/gafl-webapp-service/package-lock.json
packages/gafl-webapp-service/package.json
packages/gafl-webapp-service/src/__tests__/server-ga-integration.spec.js
packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-sales-api-failure.spec.js
packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions.spec.js
packages/gafl-webapp-service/src/plugins.js

https://eaflood.atlassian.net/browse/IWTF-3389
Hapi-Gapi has been updated to v2.0.0 ready for GA4.

Update Hapi-Gapi to v2

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/pages/errors/server-error.njk

https://eaflood.atlassian.net/browse/IWTF-3299
Add button to pre payment error page

Remove post office reference error page add button

---

packages/sales-api-service/src/__mocks__/test-data.js
packages/sales-api-service/src/services/__tests__/contacts.service.spec.js
packages/sales-api-service/src/services/contacts.service.js
packages/sales-api-service/src/services/transactions/process-transaction-queue.js

https://eaflood.atlassian.net/browse/IWTF-3170
Set so newsletter and reminder does not update when buy short term licence, emails and text data is not overriden

Short term licence confirmation

---

packages/gafl-webapp-service/src/__mocks__/request.js
packages/gafl-webapp-service/src/pages/multibuy/add-licence/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/multibuy/add-licence/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/multibuy/add-licence/result-function.js
packages/gafl-webapp-service/src/pages/multibuy/remove-licence/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/multibuy/remove-licence/update-transaction.js
packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/route.spec.js

https://eaflood.atlassian.net/browse/IWTF-3272
Empty licences in basket throwing error, remove empty licence

Remove empty licences from basket

---

packages/gafl-webapp-service/src/pages/multibuy/remove-licence/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/multibuy/remove-licence/update-transaction.js

Refactor update-transaction.spec within remove licence for multi buy

fix multibuy tests

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk

https://eaflood.atlassian.net/browse/IWTF-3489
Remove inset text on what is your date of birth? page

Remove inset text about concession age

---

packages/gafl-webapp-service/src/pages/multibuy/remove-licence/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/multibuy/remove-licence/update-transaction.js

https://eaflood.atlassian.net/browse/IWTF-3416
Error when duplicate licences in basket

Allow to delete duplicate licence

---

packages/dynamics-lib/src/entities/__tests__/__snapshots__/pocl-validation-error.entity.spec.js.snap
packages/dynamics-lib/src/entities/__tests__/pocl-validation-error.entity.spec.js
packages/dynamics-lib/src/entities/pocl-validation-error.entity.js
packages/sales-api-service/src/server/routes/__tests__/staging-exceptions.spec.js
packages/sales-api-service/src/services/exceptions/__tests__/__snapshots__/pocl-validation-errors.service.spec.js.snap
packages/sales-api-service/src/services/exceptions/__tests__/pocl-validation-errors.service.spec.js
packages/sales-api-service/src/services/exceptions/pocl-validation-errors.service.js

https://eaflood.atlassian.net/browse/IWTF-3418
Switched to defra_countrylist being the country field as that's an optionset lookup

New country field for validation errors table

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/processors/__tests__/licence-type-display.spec.js
packages/gafl-webapp-service/src/processors/licence-type-display.js
packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js

https://eaflood.atlassian.net/browse/IWTF-3537
Updating the content for when over 66 is referenced

Over 66 content

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json

https://eaflood.atlassian.net/browse/IWTF-3537
Updating age concession wording on licence details page

Update over 66 content

---

packages/gafl-webapp-service/src/pages/contact/address/entry/address-entry.njk
packages/gafl-webapp-service/src/pages/contact/address/entry/route.js

https://eaflood.atlassian.net/browse/IWTF-3675
Empty link at bottom of 'enter your address' page

Accessibility link

---

packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/check-confirmation-contact/check-confirmation-contact.njk
packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk
packages/gafl-webapp-service/src/pages/guidance/cookies.njk
packages/gafl-webapp-service/src/pages/guidance/new-prices.njk
packages/gafl-webapp-service/src/pages/guidance/os-terms.njk
packages/gafl-webapp-service/src/pages/guidance/privacy-policy.njk
packages/gafl-webapp-service/src/pages/guidance/refund-policy.njk
packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/licence-start-time.njk
packages/gafl-webapp-service/src/pages/licence-details/no-licence-required/no-licence-required.njk
packages/gafl-webapp-service/src/pages/macros/standard-form.njk
packages/gafl-webapp-service/src/pages/order-complete/licence-details/licence-details.njk
packages/gafl-webapp-service/src/pages/renewals/renewal-inactive/renewal-inactive.njk
packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk
packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
packages/gafl-webapp-service/src/pages/terms-and-conditions/terms-and-conditions.njk

https://eaflood.atlassian.net/browse/IWTF-3672
Remove back link from main content

Accessibility - back link

---

packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/check-confirmation-contact/check-confirmation-contact.njk
packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk
packages/gafl-webapp-service/src/pages/guidance/cookies.njk
packages/gafl-webapp-service/src/pages/guidance/new-prices.njk
packages/gafl-webapp-service/src/pages/guidance/os-terms.njk
packages/gafl-webapp-service/src/pages/guidance/privacy-policy.njk
packages/gafl-webapp-service/src/pages/guidance/refund-policy.njk
packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/licence-start-time.njk
packages/gafl-webapp-service/src/pages/licence-details/no-licence-required/no-licence-required.njk
packages/gafl-webapp-service/src/pages/macros/standard-form.njk
packages/gafl-webapp-service/src/pages/order-complete/licence-details/licence-details.njk
packages/gafl-webapp-service/src/pages/renewals/renewal-inactive/renewal-inactive.njk
packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk
packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
packages/gafl-webapp-service/src/pages/terms-and-conditions/terms-and-conditions.njk

Reverts DEFRA/rod-licensing#1788

Revert "Accessibility - back link"

---

packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/licence-confirmation-method.njk
packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk

https://eaflood.atlassian.net/browse/IWTF-3683
Update focus order after change button clicked

Accessibility focus order

---

packages/gafl-webapp-service/assets/sass/rod-licensing/_general.scss
packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/check-confirmation-contact/check-confirmation-contact.njk

https://eaflood.atlassian.net/browse/IWTF-3813
make the page for the low vision users who require screen magnification, ensuring that all content is accessible and easily operable for them

Content reflow

---

packages/gafl-webapp-service/src/pages/recurring-payments/set-up-payment/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/recurring-payments/set-up-payment/route.js
packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/result-function.spec.js
packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/update-transaction.spec.js
packages/gafl-webapp-service/src/pages/terms-and-conditions/result-function.js
packages/gafl-webapp-service/src/pages/terms-and-conditions/update-transaction.js
packages/gafl-webapp-service/src/processors/__tests__/recurring-pay-helper.spec.js
packages/gafl-webapp-service/src/processors/recurring-pay-helper.js

https://eaflood.atlassian.net/browse/IWTF-3898
Recurring payment is not available for BOBO so should only display if buying licence for yourself

Recurring Payment not for BOBO

---

packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
packages/gafl-webapp-service/src/processors/__tests__/price-display.spec.js
packages/gafl-webapp-service/src/processors/price-display.js

https://eaflood.atlassian.net/browse/IWTF-3933
The price on the order confirmation page is wrong when purchasing a licence where the price hasn't yet increased, but will have done by the time the licence starts, so the new price is charged but the order confirmation page shows the old price.

Price on order confirmation page incorrect

---

packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk

https://eaflood.atlassian.net/browse/IWTF-3890
Remove link for postal licence with digital confirmation

Confirmation page content

---

packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js

https://eaflood.atlassian.net/browse/IWTF-3889
display rcp content on confirmation page

Confirmation display recurring payment

---

packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
packages/gafl-webapp-service/src/processors/price-display.js

https://eaflood.atlassian.net/browse/IWTF-3990
Fix code smells that have appeared on develop branch

Code smells on develop

---

packages/sales-api-service/src/services/__tests__/permissions.service.spec.js

https://eaflood.atlassian.net/browse/IWTF-4016
Test failing as setup in test doesnt factor in leap year

Current day is leap year start licence

---

packages/gafl-webapp-service/src/processors/__tests__/renewals-write-cache.spec.js
packages/gafl-webapp-service/src/processors/renewals-write-cache.js

https://eaflood.atlassian.net/browse/IWTF-3958
When renewing a licence, they're starting a day early at 11pm

Renewing a licence starts a day early

---

packages/gafl-webapp-service/src/__tests__/server.spec.js
packages/gafl-webapp-service/src/server.js

https://eaflood.atlassian.net/browse/IWTF-3999
When open link to new prices page it opens to start of journey first

Cant access new prices page

---

packages/dynamics-lib/src/__mocks__/option-set-data.json
packages/dynamics-lib/src/entities/__tests__/recurring-payment.entity.spec.js
packages/dynamics-lib/src/entities/recurring-payment.entity.js
packages/dynamics-lib/src/index.js
packages/dynamics-lib/src/queries/__tests__/recurring-payments-queries.spec.js
packages/dynamics-lib/src/queries/recurring-payments.queries.js
packages/sales-api-service/src/services/transactions/process-transaction-queue.js

https://eaflood.atlassian.net/browse/IWTF-3617
Testing recurring payment is failing as need latest version of dynamics-lib, updating here to push to develop so can test

Update dyncamics lib recurring payment

---

packages/gafl-webapp-service/src/processors/__tests__/recurring-pay-helper.spec.js
packages/gafl-webapp-service/src/processors/recurring-pay-helper.js

https://eaflood.atlassian.net/browse/IWTF-3910
add flag check that valid for recurring pay if not a telesales

NCCC users not see RCP option

---

docker/env/recurring_payments_job.env.example
packages/recurring-payments-job/README.md
packages/recurring-payments-job/src/__tests__/recurring-payments-job.spec.js
packages/recurring-payments-job/src/recurring-payments-job.js

https://eaflood.atlassian.net/browse/IWTF-3840
Adding delay too recurring payment job so is able to access Sales API when ran

RP job local failure

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/pages/guidance/recurring-payment-terms-conditions.njk

https://eaflood.atlassian.net/browse/IWTF-4084
Since we are not planning to have this be available at release, we need to remove it from the terms and conditions.

Remove online cancellation from recurring payments terms

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/pages/guidance/privacy-policy.njk

https://eaflood.atlassian.net/browse/IWTF-3661
Adding a line of content to the privacy policy page which explains that our payment providers comply to certain data storage standards.
- English added

Amend privacy policy page for recurring card payments

---

package-lock.json

package-lock json is throwing error as saying is not in sync, running npm install and pushing to branch
error is "npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing."

github actions error

---

README.md

Node should be v14+, up to and including v18

Update Node version prerequisite in README

---

package-lock.json

https://eaflood.atlassian.net/browse/IWTF-4129
package-lock.json seems update with error every new branch

dependencies error

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json

Extended from this ticket -> https://eaflood.atlassian.net/browse/IWTF-4122

"Cost" is missing from the licence summary page

---

packages/gafl-webapp-service/src/processors/recurring-pay-helper.js

https://eaflood.atlassian.net/browse/IWTF-4066
JUNIOR_MAX_AGE is referencing business-rules-lib relatively rather than by package

Fix ages reference

---

packages/gafl-webapp-service/src/pages/guidance/cookies.njk

https://eaflood.atlassian.net/browse/IWTF-4214
remove options to accept/reject analytics from cookies page

Remove analytics button

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json

https://eaflood.atlassian.net/browse/IWTF-4203

Incorrect date on ticket (already merged)

---

packages/business-rules-lib/src/validators/__tests__/date.validators.spec.js
packages/business-rules-lib/src/validators/date.validators.js

https://eaflood.atlassian.net/browse/IWTF-3913
This adds additional validators for the individual date fields and the overall date to make sure that any dates entered are valid.
An additional PR will follow to apply these validations to the GAFL frontend.

Add new validators for date fields

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json

https://eaflood.atlassian.net/browse/IWTF-4185
Following review by Jen, some minor changes on page "When would you like your licence to start?" are needed to make the service more consistent and grammatically correct.

Minor Content Change To start-kind Page

---

packages/business-rules-lib/src/index.js

https://eaflood.atlassian.net/browse/IWTF-3941

Export date validations

---

packages/business-rules-lib/src/validators/__tests__/contact.validators.spec.js
packages/business-rules-lib/src/validators/contact.validators.js

https://eaflood.atlassian.net/browse/IWTF-4146
prevent users from copying and pasting non standard fonts into input fields

Copy and paste into input fields

---

.prettierignore
packages/recurring-payments-job/package-lock.json

https://eaflood.atlassian.net/browse/IWTF-4249
Update dependencies of recurring payments job

RCP Job Fails Locally

---

packages/dynamics-lib/src/queries/permission.queries.js
packages/sales-api-service/src/server/routes/__tests__/__snapshots__/renewals.spec.js.snap
packages/sales-api-service/src/server/routes/__tests__/renewals.spec.js
packages/sales-api-service/src/server/routes/renewals.js

https://eaflood.atlassian.net/browse/IWTF-3916
Transaction creation is failing due to lack of proof, so fixing that

Amend transaction creation payload

---

packages/gafl-webapp-service/src/routes/__tests__/misc-routes-handlers.spec.js
packages/gafl-webapp-service/src/routes/misc-routes.js

https://eaflood.atlassian.net/browse/IWTF-4236
set csrf token to cookies page so can save multiple times if change response

Save multiple times cookies page

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/pages/guidance/recurring-payment-terms-conditions.njk
packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk

https://eaflood.atlassian.net/browse/IWTF-4250
We have had a recommendation from DAC that our “Change” links have better descriptions for screen readers, so that users of that accessibility tech have better context.

Amend Change link in Easy Renew Journey

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/pages/contact/address/select/address-select.njk

https://eaflood.atlassian.net/browse/IWTF-4253
Change the change link to edit search on address page

Change link on address page

---

packages/gafl-webapp-service/src/pages/contact/contact/__tests__/contact.spec.js
packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
packages/gafl-webapp-service/src/pages/contact/contact/route.js
packages/gafl-webapp-service/src/pages/licence-details/licence-length/__tests__/licence-length.spec.js

https://eaflood.atlassian.net/browse/IWTF-4157
Selecting post and continue through journey it is deselected, set so when go back on page post is still selected

Fulfilment page deselecting post

---

packages/gafl-webapp-service/src/__tests__/server.spec.js
packages/gafl-webapp-service/src/server.js

https://eaflood.atlassian.net/browse/IWTF-3305
View recurring payments via hyperlink without having to go through the journey

Display Recurring payment terms and conditions

---

packages/dynamics-lib/src/index.js

https://eaflood.atlassian.net/browse/IWTF-2715
Add missing export for RCR angler login

Add missing export for RCR angler login

---

docker/infrastructure.yml

The localstack config has become out-of-date, some settings need to be updated for it to continue working

Fix localstack config

---

packages/gafl-webapp-service/package-lock.json
packages/gafl-webapp-service/package.json

https://eaflood.atlassian.net/browse/IWTF-4277
Uninstall pdfmake from gafl as it has a critical security vulnerability (crypto-js) we no longer use

Uninstall pdfmake

---

scripts/github/deploy.sh

https://eaflood.atlassian.net/browse/IWTF-4117
update deploy script to update package-lock files

Update dependencies in package-lock

---

.github/workflows/build.yml

https://eaflood.atlassian.net/browse/IWTF-3967
Update versioning script for removing set-ouput

Set-output removed from versioning script

---

packages/connectors-lib/src/__tests__/govuk-pay-api.spec.js
packages/connectors-lib/src/govuk-pay-api.js
packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js
packages/gafl-webapp-service/src/services/payment/govuk-pay-service.js

https://eaflood.atlassian.net/browse/IWTF-4373
Since the actual payments are created using the usual createPayment function, just with recurring as true.

Rename createRecurringPayment to clarify it creates agreements

---

packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js

https://eaflood.atlassian.net/browse/IWTF-4404
remove option to change licence length for a junior licence

Change length link junior licence

---

packages/sales-api-service/src/services/__tests__/recurring-payments.service.spec.js
packages/sales-api-service/src/services/recurring-payments.service.js

https://eaflood.atlassian.net/browse/IWTF-4262
A recurring payment is being created for all permissions

Fix RP creation bug

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-3913
dob_error message is incorrect in Welsh

Fix DOB message in Welsh

---

packages/dynamics-lib/src/queries/__tests__/activity.queries.spec.js
packages/dynamics-lib/src/queries/activity.queries.js

https://eaflood.atlassian.net/browse/IWTF-4401
Update activity in CRM

Update activity in CRM

---

packages/gafl-webapp-service/src/locales/cy.json

https://eaflood.atlassian.net/browse/IWTF-4410
Hidden date picker text was not translated.

Add Welsh to Hidden Date Picker Text

---

package.json
packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
packages/gafl-webapp-service/src/pages/contact/digital-licence/check-confirmation-contact/check-confirmation-contact.njk
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/__snapshots__/route.spec.js.snap
packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/route.spec.js
packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js

https://eaflood.atlassian.net/browse/IWTF-4374
Mobile phone numbers are appearing in analytics since implementing tracking change links, remove as clickable link

Mobile phone links

---

packages/recurring-payments-job/src/__tests__/recurring-payments-processor.spec.js
packages/recurring-payments-job/src/recurring-payments-processor.js
packages/recurring-payments-job/src/services/__tests__/govuk-pay-service.spec.js
packages/recurring-payments-job/src/services/govuk-pay-service.js

https://eaflood.atlassian.net/browse/IWTF-4487
Get payment id from payment creation request so we can use it to get status

Get id from payment creation request

---

packages/sales-api-service/src/schema/__tests__/recurring-payments.schema.spec.js
packages/sales-api-service/src/schema/permission.schema.js
packages/sales-api-service/src/schema/recurring-payments.schema.js
packages/sales-api-service/src/server/routes/__tests__/recurring-payments.spec.js
packages/sales-api-service/src/server/routes/recurring-payments.js

https://eaflood.atlassian.net/browse/IWTF-4057
Validate the response for recurring payments. This is in packages/sales-api-service/src/server/routes/recurring-payments.js. Add a schema for validating input in similar way to renewals authentication.

Validate RP Request

---

packages/dynamics-lib/src/queries/__tests__/recurring-payments-queries.spec.js
packages/dynamics-lib/src/queries/recurring-payments.queries.js

https://eaflood.atlassian.net/browse/IWTF-4524
recurring payment job picking up cancelled payments

RCP cancellation

---

packages/gafl-webapp-service/src/processors/__tests__/recurring-pay-helper.spec.js
packages/gafl-webapp-service/src/processors/recurring-pay-helper.js

https://eaflood.atlassian.net/browse/IWTF-4547
Adjust so when turn off rcp wont have any impact

Ability to turn off rcp

---

packages/gafl-webapp-service/src/locales/cy.json
packages/gafl-webapp-service/src/locales/en.json
packages/gafl-webapp-service/src/pages/contact/newsletter/newsletter.njk

https://eaflood.atlassian.net/browse/IWTF-4586
Remove auto selecting of newsletter and add error message when not selected

Auto amend newsletter

---

packages/dynamics-lib/src/queries/__tests__/recurring-payments-queries.spec.js
packages/dynamics-lib/src/queries/recurring-payments.queries.js

https://eaflood.atlassian.net/browse/IWTF-4513
It's defra_agreementid, not defra_agreementId.

Fix capitalisation

---

packages/recurring-payments-job/package-lock.json
packages/recurring-payments-job/package.json
packages/recurring-payments-job/src/__tests__/recurring-payments-processor.spec.js
packages/recurring-payments-job/src/recurring-payments-processor.js

https://eaflood.atlassian.net/browse/IWTF-4515
Add logging for recurring payments job

Recurring payments logging

---

packages/connectors-lib/src/__tests__/aws.spec.js
packages/connectors-lib/src/aws.js
packages/pocl-job/src/io/__tests__/s3.spec.js
packages/pocl-job/src/io/s3.js

https://eaflood.atlassian.net/browse/IWTF-3449
Updating pocl job to use AWS SDK v3

AWS SDK v3 pocl job

---

docker/README.md
package-lock.json
package.json
packages/gafl-webapp-service/Dockerfile
packages/gafl-webapp-service/assets/sass/main.scss
packages/gafl-webapp-service/assets/sass/rod-licensing/_cookie_banner.scss
packages/gafl-webapp-service/package-lock.json
packages/gafl-webapp-service/package.json
packages/gafl-webapp-service/src/pages/layout/layout.njk

https://eaflood.atlassian.net/browse/IWTF-4664
v5.10.2 of the GOV.UK front end contains branding changes. these include:

Update GAFL Frontend to v5.10.2

---

packages/dynamics-lib/src/queries/__tests__/recurring-payments-queries.spec.js
packages/dynamics-lib/src/queries/recurring-payments.queries.js

https://eaflood.atlassian.net/browse/IWTF-4657
Recurring payments job will nnot pick up recurring payments that already have next recurring payment field

Exclude completed recurring payments

---

packages/recurring-payments-job/src/__tests__/recurring-payments-processor.spec.js
packages/recurring-payments-job/src/recurring-payments-processor.js
packages/sales-api-service/src/schema/__tests__/transaction.schema.spec.js
packages/sales-api-service/src/schema/transaction.schema.js

https://eaflood.atlassian.net/browse/IWTF-4767
The RP job needs to provide the RP id so that it can be cancelled should the payment fail

 Amend RP job with RP id

---

packages/gafl-webapp-service/src/processors/__tests__/api-transaction.spec.js
packages/gafl-webapp-service/src/processors/api-transaction.js
packages/sales-api-service/src/schema/__tests__/transaction.schema.spec.js
packages/sales-api-service/src/schema/transaction.schema.js
packages/sales-api-service/src/services/__tests__/recurring-payments.service.spec.js
packages/sales-api-service/src/services/recurring-payments.service.js

A change in the schema for creating transactions has had repercussions in the Web Sales RP journey, this fixes that

Fix bug with creating RPs in Web Sales journey

---

packages/gafl-webapp-service/src/__tests__/server.spec.js
packages/gafl-webapp-service/src/server.js
packages/payment-mop-up-job/src/__tests__/payment-mop-up-job.spec.js
packages/payment-mop-up-job/src/payment-mop-up-job.js
packages/pocl-job/src/__tests__/pocl-job.spec.js
packages/pocl-job/src/pocl-job.js
packages/recurring-payments-job/src/__tests__/recurring-payments-job.spec.js
packages/recurring-payments-job/src/recurring-payments-job.js
packages/sales-api-service/src/server/__tests__/server.spec.js
packages/sales-api-service/src/server/server.js

https://eaflood.atlassian.net/browse/IWTF-4781
output version of the script when they start

Output version of service on startup

---

packages/recurring-payments-job/src/__tests__/recurring-payments-job.spec.js
packages/recurring-payments-job/src/recurring-payments-job.js

https://eaflood.atlassian.net/browse/IWTF-4689
Modify Recurring Payments job so that it logs to Errbit, by using Airbrake

Setup Recurring Payments job to log to Errbit

---

packages/recurring-payments-job/src/recurring-payments-processor.js

https://eaflood.atlassian.net/browse/IWTF-4658
We changed our mind.

Don't cancel RP if checking payment status throws error

---

packages/recurring-payments-job/src/__tests__/recurring-payments-job.spec.js
packages/recurring-payments-job/src/__tests__/recurring-payments-processor.spec.js
packages/recurring-payments-job/src/recurring-payments-job.js
packages/recurring-payments-job/src/recurring-payments-processor.js

https://eaflood.atlassian.net/browse/IWTF-4689
We need to refactor the RCP job so that error notifications are sent to Errbit via Airbrake

Refactor for Airbrake integration
