DEFRA/rod-licensing

- packages/sqs-receiver-service/__tests__/sqs-receiver-service.spec.js
- packages/sqs-receiver-service/ecosystem.config.yml
- packages/sqs-receiver-service/package.json
- packages/sqs-receiver-service/src/sqs-receiver-service.js
Move sqs-receiver main script file into src folder (to fix sonar coverage and ensure all source files are kept inside the src directory)
> Move sqs-receiver main script file into src folder (fix sonar coverage)

- packages/business-rules-lib/src/index.js
- packages/business-rules-lib/src/util/__tests__/ages.spec.js
- packages/business-rules-lib/src/util/ages.js
- packages/business-rules-lib/src/validators/__tests__/contact.spec.js
- packages/business-rules-lib/src/validators/contact.js
- packages/dynamics-lib/src/entities/__tests__/recurring-payment-instruction.entity.spec.js
- packages/dynamics-lib/src/entities/recurring-payment-instruction.entity.js
- packages/gafl-webapp-service/package.json
- packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry-spec.js
- packages/gafl-webapp-service/src/pages/contact/address/lookup/__tests__/address-lookup.spec.js
- packages/gafl-webapp-service/src/pages/contact/date-of-birth/__tests__/date-of-birth.spec.js
- packages/gafl-webapp-service/src/pages/contact/date-of-birth/update-transaction.js
- packages/gafl-webapp-service/src/pages/contact/name/__tests__/name.spec.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-start-date/__tests__/licence-start-date.spec.js
- packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
- packages/sales-api-service/src/schema/__tests__/transaction.schema.spec.js
- packages/sales-api-service/src/schema/contact.schema.js
- packages/sales-api-service/src/schema/permission.schema.js
- packages/sales-api-service/src/schema/validators/__tests__/index.spec.js
- packages/sales-api-service/src/schema/validators/index.js
- packages/sales-api-service/src/server/routes/__tests__/transactions.spec.js
- packages/sales-api-service/src/services/__tests__/permissions.service.spec.js
- packages/sales-api-service/src/services/permissions.service.js
- packages/sales-api-service/src/services/reference-data.service.js
- packages/sales-api-service/src/services/transactions/process-transaction-queue.js
**Move age determinators into business-rules-lib**
- Add shared age-category determinator methods
- Refactor sales-api and frontend webapp to use these
**Remove referenceNumber/defra_name from RecurringPaymentInstruction**
- Not required
**Add concession/permit validation and improve shared validation:**
- Add validator API to check:
- any concessionId provided is valid for its corresponding permitId
- a concession is present where required by a given permitId
- Update API to use shared validators wherever possible
- Align shared validation rules max length rules with Dynamics
- Use title-case for user data as per current service
> Improve shared business-rules and add concession/permit validation

- packages/gafl-webapp-service/src/routes/static-routes.js
When running the GAFL webapp from a directory other than the root of the
webapp (packages/galf-webapp-service), static files such as main.css,
all-min.js, etc, fail to serve
> Static files failing to serve

- package.json
- Move from post-checkout to post-merge to ensure hooks run after git pull
- Use --skip-worktree rather than --assume-unchanged for secrets.env files to avoid overwriting local customisations
> Revise git commit hooks to fix issues with sftp keys and secrets.env files

- packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry-spec.js
- packages/gafl-webapp-service/src/pages/contact/address/entry/update-transaction.js
- packages/gafl-webapp-service/src/pages/contact/contact/update-transaction.js
- packages/gafl-webapp-service/src/pages/contact/newsletter/update-transaction.js
- packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
- packages/gafl-webapp-service/src/pages/renewals/identify/__mocks__/data/authentication-result.js
- packages/gafl-webapp-service/src/processors/renewals-write-cache.js
- packages/sales-api-service/src/schema/contact.schema.js
(1) If an organisation is set (from pocl) for the licence being renewed it is retained (but not seen) unless the address is changed.
(2) If the user changes the method of reminder from email to mobile or vice-versa, then the old method is deleted from the CRM.
(3) Fix bug where non-mandatory address fields set null from the renewal data were not validated ok by the sales-api. These are now joi.allow(null) in the api.
> Changes to renewals procedure: fixes and changes around non-mandatory fields

- packages/gafl-webapp-service/src/pages/layout/layout.njk
- packages/gafl-webapp-service/src/server.js
When a custom cookie name is configured for the CsrfToken then this wasn't matching what was inserted into the form via the templates.
> Fix issue with CSRF token when a custom CSRF cookie name is set

- packages/business-rules-lib/src/validators/permission.js
- packages/gafl-webapp-service/package-lock.json
- packages/gafl-webapp-service/package.json
- packages/gafl-webapp-service/src/__tests__/server-test-sanitize.js
- packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
- packages/gafl-webapp-service/src/handlers/attribution-handler.js
- packages/gafl-webapp-service/src/pages/contact/name/__tests__/name.spec.js
- packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk
- packages/gafl-webapp-service/src/pages/renewals/identify/route.js
- packages/gafl-webapp-service/src/plugins.js
- packages/gafl-webapp-service/src/server.js
(1) Changed the ordering of the messages on the renewals page.
(2) Relax validation of reference number to allow old licence numbers to be renewed
(3) Add input sanitisation - removed existing function around the attribution handler - 
this; http://0.0.0.0:3000/buy/attribution?utm_campaign='<script>HACK!!!</script>'&utm_medium='This is ok'
Is safe, as are inputs via the payload.
Note that disinfect simply removes anything that could be a script; <, > etc is escaped but  <.*> is replaced by ''. 
(4) Extracted the plugins to another file - server.js was getting too long
> Adjust licence validator, introduce disinfect library, refactoring improvements

- docker/env/sqs_receiver.env
- packages/pocl-job/src/staging/__tests__/create-transactions.spec.js
- packages/pocl-job/src/staging/__tests__/finalise-transactions.spec.js
- packages/pocl-job/src/staging/constants.js
- packages/pocl-job/src/staging/create-transactions.js
- packages/pocl-job/src/staging/finalise-transactions.js
- packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
- packages/sales-api-service/src/services/transactions/finalise-transaction.js
- packages/sqs-receiver-service/README.md
- packages/sqs-receiver-service/src/process-message.js
- packages/sqs-receiver-service/src/receiver.js
**Remove routing based on MessageGroupId and revise poll delay logic**
- Avoid using the same MessageGroupId for all messages
- Avoid queue being blocked if one message fails to be delivered
- Fix issue with poll delay logic to allow delay to be increased incrementally
**Reduce batch size of concurrent finalise transaction requests in POCL job**
- Separate batch size for create transaction and finalise transaction calls
> Performance tuning of SQS integration and POCL job

- packages/dynamics-lib/package-lock.json
- packages/dynamics-lib/package.json
- packages/dynamics-lib/src/client/dynamics-client.js
Issue described here: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/239
> Workaround for bug in adal-node failing to cache tokens and leaking memory

- packages/dynamics-lib/src/entities/__tests__/concession-proof.entity.spec.js
- packages/dynamics-lib/src/entities/concession-proof.entity.js
- packages/dynamics-lib/src/queries/__tests__/fulfilment.queries.spec.js
- packages/dynamics-lib/src/queries/__tests__/permission.queries.spec.js
- packages/dynamics-lib/src/queries/__tests__/predefined-query.spec.js
- packages/dynamics-lib/src/queries/permission.queries.js
- packages/dynamics-lib/src/queries/predefined-query.js
- packages/gafl-webapp-service/src/pages/renewals/identify/__mocks__/data/authentication-result.js
- packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
- packages/gafl-webapp-service/src/processors/renewals-write-cache.js
- packages/sales-api-service/src/server/routes/__tests__/authenticate.spec.js
- packages/sales-api-service/src/server/routes/authenticate.js
- packages/sales-api-service/src/services/transactions/process-transaction-queue.js
- Concession id now exposed
- Modified structure of response to more closely match the create transaction schema
- Frontend updated to process new structure
> Expose concession id in renewals authentication response

- packages/gafl-webapp-service/src/pages/layout/layout.njk
- packages/gafl-webapp-service/src/plugins.js
This fixes IE11. 
The unsafe-inline directive is ignored on modern browsers where nonces are set so this does not undermine the CSP.
IE11 does not support CSP, removing the nonce from the tag and setting 'self' allows all-min.js to run. This ran with the nonce on FF and Chrome anyway but this is now correct I think.
Tested on IE11 and Safari back to Snow Leopard. Allso some adhoc tests: FF and the Galaxy S3.
> Fix IE11 problem

- packages/gafl-webapp-service/src/handlers/renewal-start-date-validation-handler.js
- packages/gafl-webapp-service/src/pages/concessions/date-of-birth/update-transaction.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-length/update-transaction.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/route.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/update-transaction.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-type/update-transaction.js
- packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
- packages/gafl-webapp-service/src/processors/date-and-time-display.js
- packages/gafl-webapp-service/src/processors/renewals-write-cache.js
If a 12 month licence is indirectly by changing (a) age, (b) type=3-rod, (c) the length then if the licence is starting later today, always set the 'after-payment' flag
> Fix: all indirect methods of selecting a 12 month licence 

- packages/gafl-webapp-service/src/processors/refdata-helper.js
- packages/gafl-webapp-service/src/server.js
(1) Filter out the home countries from the drop down on the front end
(2) Do not show the cookie password in the debug.
> Filter non-iso compliant entries from countries list

- packages/gafl-webapp-service/assets/sass/rod-licensing/_calendar.scss
- packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
Calendar does not work on IE due to div:content different behaviour. Change to use standard image.
> Fix calendar noshow on IE11

- packages/dynamics-lib/src/client/__tests__/cache.spec.js
- packages/dynamics-lib/src/client/cache.js
- packages/dynamics-lib/src/index.js
- packages/pocl-job/src/staging/__tests__/finalise-transactions.spec.js
- packages/pocl-job/src/staging/finalise-transactions.js
- packages/pocl-job/src/transform/bindings/pocl/licence/licence.bindings.js
- packages/sales-api-service/src/schema/transaction.schema.js
- packages/sales-api-service/src/schema/validators/__tests__/validators.spec.js
- packages/sales-api-service/src/schema/validators/validators.js
- packages/sales-api-service/src/server/routes/transactions.js
- packages/sales-api-service/src/server/server.js
- packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
- packages/sales-api-service/src/services/transactions/finalise-transaction.js
- packages/sales-api-service/src/services/transactions/retrieve-transaction.js
- Ensure POCL process resumes correctly when running finalisation (HTTP 410 Gone errors now treated as a success case (not resulting in a staging exception being raised)
- Cache permits in local memory once retrieved from the Sales API
- Update SalesAPI to allow the existence of a transaction file to be cached for a period of time to reduce calls to Dynamics when processing POCL files
> Improvements to POCL loader to ensure process is resumable and improve efficiency 

- packages/gafl-webapp-service/assets/sass/rod-licensing/_calendar.scss
- packages/gafl-webapp-service/build/gulpfile.cjs
- packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
Some css changes to colour code the next and previous month dates and to increase the text size to .9em which imho looks a lot better. I think we can give this to Jon also to check over. 
Do not display the year input control, it does not really work very well. Replace it with a ready only year which is updated by the arrows, '<' and '>'.
Added a toggle action to the icon.
Tested on old browsers and passed by HD.
> Improve the look of the calendar control

- packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry-spec.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-length/update-transaction.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/licence-to-start.spec.js
Fix: Licence to start future --> 8 day licence --> 4pm --> 12 month --> start time = 4pm
Now: Licence to start future --> 8 day licence --> 4pm --> 12 month --> start time = midnight
and - no regression on
Fix: Licence to start later today --> 8 day licence --> 4pm --> 12 month --> start time = after payment
Unit tests for this
Fix uncovered line in result function
> Fix length issue and add coverage

- packages/business-rules-lib/src/validators/__tests__/contact.validators.spec.js
- packages/business-rules-lib/src/validators/contact.validators.js
- Improve efficiency by only iterating the string once to perform substitutions
- Improve substitution lists to handle alternative characters more effectively (e.g. alternative characters for an apostrophe)
- Improve handling of minimum length rules
- expect minimum number of alpha characters rather than minimum length (e.g. block `..` or `.-.`)
- Improve standardisation of spacing
- Revise allowed characters based on PO test data
> Improve contact first/last name validation rules

- packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
- packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
- packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk
Change to contact summary - display 'make a note of the licence number on confirmation'
Fix order-complete template logic to display 'Application complete' for a junior journey.
Additional code coverage on easy renewals
> Fix content

- packages/gafl-webapp-service/src/pages/layout/layout.njk
https://eaflood.atlassian.net/browse/IWTF-1453
The cookie name to indicate acceptance of cookie usage needs to change to match what's stated on the cookie guidance page
> Amend accept cookies cookie name

- packages/gafl-webapp-service/src/pages/contact/name/name.njk
Change the error messages given in the name page - this is a little tricky but at this stage in the game not suitable to major surgery. 
The was a little ambiguous  - simplified to the following:
(1) 'Your first name must contain at least 2 letters' (for char count < 2 after exclusions)
(2) 'our first name must not be longer than 100 letters' (For the processed name)
(3) 'Your first name must only contain letters' - only if length requirements are met and name contains disallowed
> Change error messages on name page

- docker/env/fulfilment_job.env
- packages/connectors-lib/src/__tests__/distributed-lock.spec.js
- packages/connectors-lib/src/distributed-lock.js
- packages/dynamics-lib/src/client/__tests__/cache.spec.js
- packages/dynamics-lib/src/client/cache.js
- packages/fulfilment-job/src/__tests__/fulfilment-processor.spec.js
- packages/fulfilment-job/src/fulfilment-processor.js
- packages/fulfilment-job/src/staging/__tests__/create-part-files.spec.js
- packages/fulfilment-job/src/staging/__tests__/deliver-fulfilment-files.spec.js
- packages/fulfilment-job/src/staging/create-part-files.js
- packages/fulfilment-job/src/staging/deliver-fulfilment-files.js
- packages/payment-mop-up-job/src/__tests__/payment-mop-up-job.spec.js
- packages/payment-mop-up-job/src/payment-mop-up-job.js
- packages/pocl-job/src/__tests__/pocl-processor.spec.js
- packages/pocl-job/src/pocl-processor.js
**Improve behaviour of ETL jobs with regard to locking and shutdown**
- Fix issue with fulfilment job not shutting down due to cache manager in dynamics-lib
- Ensure ETL tasks output a message and then exit with code 0 if process already locked
**Fulfilment: Fix sequence no. generator and deliver files in sequence**
- Sequence number generator now uses the filename to determine the next sequence number
- Fulfilment files are now delivered in sequence number order
> Updates and fixes to the ETL tasks

- packages/sales-api-service/src/schema/__tests__/transaction.schema.spec.js
- packages/sales-api-service/src/schema/contact.schema.js
- packages/sales-api-service/src/schema/permission.schema.js
- packages/sales-api-service/src/schema/transaction.schema.js
- packages/sales-api-service/src/schema/validators/__tests__/validators.spec.js
- packages/sales-api-service/src/schema/validators/validators.js
- No longer checks concession proof for P.O. sales
- No longer requires postcode for P.O. sales
> Relax validation rules for Post Office sales

- packages/connectors-lib/package-lock.json
- packages/connectors-lib/package.json
- packages/connectors-lib/src/__tests__/airbrake.spec.js
- packages/connectors-lib/src/airbrake.js
- packages/connectors-lib/src/connectors.js
- packages/fulfilment-job/src/__tests__/fulfilment-processor.spec.js
- packages/fulfilment-job/src/fulfilment-processor.js
- packages/gafl-webapp-service/src/__tests__/gafl-webapp-service.spec.js
- packages/gafl-webapp-service/src/__tests__/server.spec.js
- packages/gafl-webapp-service/src/handlers/error-handler.js
- packages/gafl-webapp-service/src/server.js
- packages/payment-mop-up-job/src/payment-mop-up-job.js
- packages/pocl-job/src/__tests__/pocl-processor.spec.js
- packages/pocl-job/src/pocl-processor.js
- packages/sales-api-service/src/server/__tests__/server.spec.js
- packages/sales-api-service/src/server/server.js
- packages/sqs-receiver-service/ecosystem.config.yml
- packages/sqs-receiver-service/src/__tests__/sqs-receiver-service.spec.js
- packages/sqs-receiver-service/src/sqs-receiver-service.js
- connectors-lib now provides airbrake support to services
- console.error & console.warn now send notifications to airbrake
- all services updated to initialise airbrake on startup
- all services updated to flush airbrake notifications on shutdown
- issue with sqs receiver not shutting down gracefully fixed
- sqs receiver pm2 configuration changed to allow current operations to complete
> Add airbrake support all services

- packages/gafl-webapp-service/src/__tests__/server-ga-integration.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
- packages/gafl-webapp-service/src/handlers/attribution-handler.js
- packages/gafl-webapp-service/src/handlers/new-session-handler.js
- packages/gafl-webapp-service/src/plugins.js
- packages/gafl-webapp-service/src/processors/__tests__/analytics.spec.js
- packages/gafl-webapp-service/src/processors/analytics.js
- packages/gafl-webapp-service/src/routes/misc-routes.js
- packages/gafl-webapp-service/src/session-cache/session-manager.js
- Ensure invocations of the `/buy/new` endpoint read the _ga parameter and store this data on the session to enable cross-domain tracking support (from the GOV.UK landing page)
- Ensure the session manager (onPreHandler) also respects the _ga parameter (and store this data on the session) as this will intercept invocations of `/buy/new` if a session doesn't already exist
- Ensure that the previous session's attribution data is copied to the new session when `/buy/new` is invoked
- Update the hapi-gapi plugin sessionIdProducer method to pass through the gaSessionId from the session data if available, else pass through the standard session identifier
- Remove console.warn calls when hitting the attribution endpoint without the required parameters as this is a client error and these will …
> Enable x-domain analytics tracking & persist attribution between sessions

- packages/gafl-webapp-service/src/handlers/agreed-handler.js
https://eaflood.atlassian.net/browse/IWTF-1569
From time to time, the call to salesApi.createTransaction fails saying
birthDate is before the minimum date. We've been unable to track down
what's causing this, so we need to add more logs to give us a bit more
information
> Add logs to diagnose create transaction failure

- packages/gafl-webapp-service/src/pages/layout/layout.njk
Fixes the issue where the cookie banner has been dismissed with the ‘Close' button but reappears when opening the guidance pages.
> Explicitly set the path for the banner cookie

- packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/licence-start-time.njk
https://eaflood.atlassian.net/browse/IWTF-1717
The heading reads "Choose when you would like the licence to start on Friday, 18th December, 2020?" This looks unprofessional and is grammatically incorrect
> Remove question mark from text

- packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
https://eaflood.atlassian.net/browse/IWTF-1719
When buying a licence on mobile and entering a contact email address to send the licence to, we should show an "email" keyboard which contains an @ to help people enter their email address.
> Show correct keyboard for email addresses

- packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/__tests__/renewal-start-date.spec.js
https://eaflood.atlassian.net/browse/IWTF-1714
The test fails because at the beginning the endDate is set to 2hrs before the current time. This works out to be yesterday if the test is run between 12am or 1am.
> Test fails if run between 12AM - 1AM GMT

- packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
- packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
- packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk
The service currently has a 10 day SLA to send the licence in the post to anglers which is increasing to 15 days
> Change the licence SLA from 10 days to 15 days

- packages/dynamics-lib/src/__mocks__/dynamics-web-api-mock-helper.js
- packages/dynamics-lib/src/client/__tests__/entity-manager.spec.js
- packages/dynamics-lib/src/client/entity-manager.js
Instead of trying to calculate whether to do an insert or update call, we perform an upset to avoid duplicate key errors in dynamics.
> Use an upsert transaction for dynamics

- packages/gafl-webapp-service/src/processors/__tests__/analytics.spec.js
- packages/gafl-webapp-service/src/processors/analytics.js
https://eaflood.atlassian.net/browse/IWTF-2023
How we obtain the client id for tracking seems to be based on a misapprehension. We need to obtain the client id for tracking
correctly, but also in a manner that fails gracefully in case:
1) I'm wrong about how _ga is formatted
2) The way that _ga is put together should ever change in the future
> Fix how we obtain client tracking id

- packages/dynamics-lib/src/client/__tests__/entity-manager.spec.js
- packages/dynamics-lib/src/client/entity-manager.js
- packages/fulfilment-job/src/staging/__tests__/create-part-files.spec.js
- packages/fulfilment-job/src/staging/__tests__/deliver-fulfilment-files.spec.js
- packages/fulfilment-job/src/staging/create-part-files.js
- packages/fulfilment-job/src/staging/deliver-fulfilment-files.js
- packages/gafl-webapp-service/src/processors/api-transaction.js
- packages/sales-api-service/src/schema/transaction.schema.js
- packages/sales-api-service/src/server/routes/__tests__/transaction-files.spec.js
- packages/sales-api-service/src/server/routes/transaction-files.js
- packages/sales-api-service/src/services/exceptions/__tests__/exceptions.service.spec.js
- packages/sales-api-service/src/services/exceptions/exceptions.service.js
- packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
- packages/sales-api-service/src/services/transactions/process-transaction-queue.js
When a telesales user creates a new licence, their oid (dynamics user ID) will be passed through to the sales API in the 'createdBy' field, which will allow our dynamics code to impersonate that user when creating the licence and associated objects. The oid will be stored with the transaction on the SQS queue and then in dynamodb, before being used to impersonate the user when calling dynamics. Any records without a createdBy field will call dynamics in the normal way.
This change allows us to have an audit trail for telesales transactions.
> Pass through telesales user ids to sales api

- packages/gafl-webapp-service/src/processors/__tests__/refdata-helper.spec.js
- packages/gafl-webapp-service/src/processors/refdata-helper.js
https://eaflood.atlassian.net/browse/IWTF-2074
Paragon only send bilingual licences to licensees with the country field set to 'Wales'. This is set automatically when the postcode lookup is used, however many Welsh postcodes result in an error from the lookup service (see IWTF-2072). Therefore, customers living in Wales need to be able to select 'Wales' in the manual address entry and are forced to
choose 'United Kingdom', meaning they can never receive a bilingual licence
> Reinstate home countries in address entry

- .github/workflows/build.yml
The versioning script that runs on a commit to develop doesn't seem to handle single quote characters in the commit message
> Fix version script when commit message contains single quotes

- packages/gafl-webapp-service/src/pages/contact/address/entry/route.js
https://eaflood.atlassian.net/browse/IWTF-2083
IWTF-2074 added in the home nations, but didn't include postcode
validation. This change will add that in
> Postcode validation for UK nations

- packages/gafl-webapp-service/src/processors/__tests__/payment.spec.js
- packages/gafl-webapp-service/src/processors/payment.js
IWTF-2170
* Adds conditonal logic to prefilled billing address
* Adds tests for payment.js
> Fix: Only pass street name to GovPay if provided

- packages/fulfilment-job/src/staging/create-part-files.js
- packages/fulfilment-job/src/transport/__tests__/s3.spec.js
- packages/fulfilment-job/src/transport/s3.js
When decrypting the encrypted fulfilment file, we were ending up with the utf character codes rather than the actual characters. It turns out this is because the encoding hadn't been set on the readable stream - somehow we've got away with this so far, but when the readable stream is fed into openpgp to be transformed into an encrypted readable stream, this will end up with just the utf codes in the stream rather than the characters.
> Fulfilment encryption utf encoding bug

- docker/infrastructure.yml
Localstack has started throwing errors on redirect to GovPay, this rolls us back to a version where this still worked
> Fix localstack to last working version

- packages/sales-api-service/src/schema/staging-exception.schema.js
IWTF-2175
* Loosens validators in updatePoclValidationError payload schema to allow errors in data
> Fix: update POCL validation errors payload schema

- docker/infrastructure.yml
https://eaflood.atlassian.net/browse/IWTF-2268
We pinned localstack to v0.12.12 as we started to hit problems. It looks like these have been fixed, so we can go back to using the latest version now
> Restore localstack to latest release

- packages/gafl-webapp-service/src/routes/__tests__/back-links.spec.js
- packages/gafl-webapp-service/src/routes/journey-definition.js
https://eaflood.atlassian.net/jira/software/c/projects/IWTF/boards/440?modal=detail&selectedIssue=IWTF-2726
This fixes an issue where the back button from the address lookup page goes back to the name page where it should go to licence summary.
> Fix for back button from address lookup page

- packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/licence-fulfilment.njk
https://eaflood.atlassian.net/browse/IWTF-2740
Link to annual fishery report directs to 19/20 report and needs to now go to 20/21.
> Update link to annual fishery report

- packages/gafl-webapp-service/src/locales/en.json
https://eaflood.atlassian.net/browse/IWTF-2778
Text for how should we contact page needs to be less generic stating 'the licence holder' rather than you/they.
> Update how should we contact person page

- packages/gafl-webapp-service/src/locales/cy.json
- packages/gafl-webapp-service/src/locales/en.json
https://eaflood.atlassian.net/browse/IWTF-2778
Confirmation method page has incorrect title when buying for someone else.
> Fix for incorrect title on confirmation method page

- packages/gafl-webapp-service/src/pages/contact/address/entry/address-entry.njk
https://eaflood.atlassian.net/browse/IWTF-2796
The postcode hint for enter address was not pushed to github and is required.
> Fix missing postcode hint in address entry

- packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/licence-confirmation-method.njk
https://eaflood.atlassian.net/browse/IWTF-2803
As an Angler buying for some one else and having chosen the paperless option,
I want the ability to determine how the fishing licence is delivered
So that I can choose how the licence is received.
> Where should we send the fishing licence

- packages/gafl-webapp-service/src/pages/guidance/cookies.njk
https://eaflood.atlassian.net/browse/IWTF-2851
The back link on the cookies page needs does not go back to correct previous page.
> Bug fix for cookies page backlink

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-2822
BOBO date of birth requires additional translation that is missing.
> Fix for missing translation on BOBO date of birth page

- packages/gafl-webapp-service/src/handlers/result-functions.js
https://eaflood.atlassian.net/browse/IWTF-2882
The result function called for licence for page by updating the result function handler
> Result function not called for licence for page

- .github/dependabot.yml
As a part of developing a better strategy for keeping us up-to-date with dependabot pull requests, this will enable us to merge them to a version-updates branch that will run parallel to develop, but represent a sandbox so that we can run acceptance (and any other necessary) tests against updates and easily rollback without contaminating the commit history of the develop branch.
> Update target branch for dependabot PRs

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-2905
This button is shown when the user doesn't need to pay for the licence. This change adds the Welsh translation.
> Update button text for licence terms page

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-2915
The title text when selecting a start date for another person's licence has been changed.
> Update Welsh text when selecting licence start date

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-2735
The title attribute for the accessibility statement page now has a Welsh translation available.
> Add Welsh translation for accessibility statement title

- packages/gafl-webapp-service/src/locales/en.json
- packages/gafl-webapp-service/src/pages/layout/layout.njk
https://eaflood.atlassian.net/browse/IWTF-2850
This undoes the changes from https://github.com/DEFRA/rod-licensing/pull/1329 as the AC has now changed.
Note that the Welsh translations have not been modified as we were missing the translation for "opens in a new tab" anyway.
> Open footer link to OS terms in same window

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-2965
This PR fixes a minor text error in the Welsh translation for the disability concessions form.
> Modify Welsh text on concessions page

- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
- packages/gafl-webapp-service/src/handlers/agreed-handler.js
- packages/gafl-webapp-service/src/processors/__tests__/payment.spec.js
- packages/gafl-webapp-service/src/processors/payment.js
- packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js
https://eaflood.atlassian.net/browse/IWTF-2897
If a user has chosen to use the service in Welsh, we still want the service to be in Welsh when they return from using GovPay. This PR updates the return URL we send to GovPay to include the language change when needed.
> Include user's chosen language in GovPay return URL

- packages/gafl-webapp-service/src/processors/__tests__/payment.spec.js
- packages/gafl-webapp-service/src/processors/payment.js
- packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js
https://eaflood.atlassian.net/browse/IWTF-2897
If the user has chosen to use the Welsh language for our service, it should also be used for GOV.UK Pay too.
> Pass current language to GOV.UK Pay API

- packages/sales-api-service/src/services/__tests__/permissions.service.spec.js
- packages/sales-api-service/src/services/permissions.service.js
https://eaflood.atlassian.net/browse/IWTF-2889
12-month licences should expire at 23:59 on the eve of the anniversary of purchase.
For example, if I bought a licence today on 1 August 2022, it would expire at 23:59 on 31 July 2023.
> Update end date and time rules for 12-month licences

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-3021
The welsh translation for mobile phone is missing on multiple pages. This is set by a label in the cy.json file, so this requires updating to update all pages.
> Update welsh translation for 'mobile phone'

- packages/gafl-webapp-service/src/handlers/renewal-start-date-validation-handler.js
- packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/__tests__/renewal-start-date.next-page.spec.js
- packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/route.js
https://eaflood.atlassian.net/browse/IWTF-2995
When the Welsh langugage is selected and validation fails on the Renewals licence start page, the selected language isn't persisted and the page switches back to English
> Language doesn't persist on Renewals licence start

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-3030
There was a spelling mistake in this line about receiving Personal Independence Payment or DLA.
> Fix typo in Welsh translation

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-3031
This PR makes a minor text change so that the Welsh language journey for a customer buying on behalf of someone else reads correctly.
> Amend Welsh translation on licence start page

- packages/gafl-webapp-service/src/pages/contact/address/select/__tests__/route.spec.js
- packages/gafl-webapp-service/src/pages/contact/address/select/route.js
https://eaflood.atlassian.net/browse/IWTF-2977
The link from the address selection page to manually enter an address would previously default to English. This PR fixes that issue so the user can continue to use the service in their preferred language.
> Keep selected language when clicking manual address link

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-3044
This fixes a heading change which was accidentally reverted.
> Fix Welsh heading for licence type page

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-3039
This makes a minor change to the Welsh text about National Insurance numbers.
> Amend Welsh translation for disability concession text

- packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
- packages/gafl-webapp-service/src/handlers/page-handler.js
https://eaflood.atlassian.net/browse/IWTF-3083
The licence details page (accessed from the payment confirmation page) has the analytics banner, when it should be hidden
> Hide analytics banner on licence details page

- packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
- packages/gafl-webapp-service/src/pages/renewals/identify/route.js
https://eaflood.atlassian.net/browse/IWTF-2899
The "get a new fishing licence" link from the renewals journey was not persisting the user's chosen language - for example, if the user had previously selected Welsh, the link swapped them back to English. This PR fixes that.
It also includes some test refactoring to break up some of the tests to be a bit more granular.
> Use chosen language when moving from renewals to new licence journey

- packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
- packages/gafl-webapp-service/src/handlers/page-handler.js
https://eaflood.atlassian.net/browse/IWTF-3094
We assume that the analytics values are set in the cache by the time the page is about to be displayed, but some errors are occurring to indicate that this is not the case. We need to code more defensively to account for this
> Analytics Banner 500 error

- packages/gafl-webapp-service/src/__mocks__/request.js
- packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/__snapshots__/route.spec.js.snap
- packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/route.spec.js
- packages/gafl-webapp-service/src/pages/multibuy/view-licences/route.js
- packages/gafl-webapp-service/src/pages/multibuy/view-licences/view-licences.njk
https://eaflood.atlassian.net/browse/IWTF-3002
The value for 'Start date' on the view licence page should display '30 minutes after payment' when this option has been selected.
> View licence page missing '30 minutes after payment' in start date

- packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/route.spec.js
- packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/route.spec.js
- packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/route.spec.js
A new, custom matcher has been added for the GetDataRedirect error, so we need to refactor tests that up until now have only been checking for the type of error thrown and not for the url that's set on these errors
> GetDataRedirect test refactor

- packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/__snapshots__/route.spec.js.snap
- packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/route.spec.js
- packages/gafl-webapp-service/src/pages/multibuy/view-licences/route.js
- packages/gafl-webapp-service/src/pages/multibuy/view-licences/view-licences.njk
- packages/gafl-webapp-service/src/processors/__tests__/date-and-time-display.spec.js
- packages/gafl-webapp-service/src/processors/date-and-time-display.js
https://eaflood.atlassian.net/browse/IWTF-3002
When the user adds additional licences with future start dates, the start time text for "30 minutes after" should remain for previous licences.
> Start after 30 minutes text not showing with additional licences

- packages/gafl-webapp-service/src/processors/__tests__/date-and-time-display.spec.js
- packages/gafl-webapp-service/src/processors/date-and-time-display.js
https://eaflood.atlassian.net/browse/IWTF-3002
The date and time display tests cannot find a module in the test environment. They will need to be updated for it to work in this environment.
> Fix for breaking test environment, date and time display test issue

- docker/infrastructure.yml
Localstack v1.3.0 was released yesterday. This included some breaking changes for us - the `DEFAULT_REGION` env var has been deprecated and the location of the init scripts appears to have changed. I wasn't able to immediately fix this so pinning to an earlier working version for now, as I think we'll need a Jira ticket to properly upgrade it.
> Pin Docker to localstack v1.2.0

- packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/route.spec.js
- packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
https://eaflood.atlassian.net/browse/IWTF-3192
When selecting to modify the licence from the contact summary, the language selection isn't persisted
> Persist lang from Contact to Licence Summary

- packages/gafl-webapp-service/src/handlers/__tests__/error-testing-handler.spec.js
- packages/gafl-webapp-service/src/handlers/error-testing-handler.js
- packages/gafl-webapp-service/src/routes/__tests__/__snapshots__/error-test-routes.spec.js.snap
- packages/gafl-webapp-service/src/routes/__tests__/error-test-routes.spec.js
- packages/gafl-webapp-service/src/routes/__tests__/routes.spec.js
- packages/gafl-webapp-service/src/routes/error-test-routes.js
- packages/gafl-webapp-service/src/routes/routes.js
- packages/gafl-webapp-service/src/uri.js
https://eaflood.atlassian.net/browse/IWTF-3123
This PR adds a new route for testing specific error response codes. So going to /buy/throw-error?error=401 will return a 401 response code, etc.
The env var ERROR_PAGE_ROUTE must be set to true for it to work.
> Trigger specific error response codes from route

- packages/gafl-webapp-service/src/__tests__/server.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/analytics-handler.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/authentication-handler.redirect.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/new-session-handler.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/oidc-handler.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/renewal-start-date-validation-handler.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/renewals-friendly-url-handler.spec.js
- packages/gafl-webapp-service/src/handlers/agreed-handler.js
- packages/gafl-webapp-service/src/handlers/analytics-handler.js
- packages/gafl-webapp-service/src/handlers/attribution-handler.js
- packages/gafl-webapp-service/src/handlers/authentication-handler.js
- packages/gafl-webapp-service/src/handlers/controller-handler.js
- packages/gafl-webapp-service/src/handlers/new-session-handler.js
- packages/gafl-webapp-service/src/handlers/oidc-handler.js
- packages/gafl-webapp-service/src/handlers/page-handler.js
- packages/gafl-webapp-service/src/handlers/renewal-start-date-validation-handler.js
- packages/gafl-webapp-service/src/handlers/renewals-friendly-url-handler.js
- packages/gafl-webapp-service/src/routes/__tests__/misc-routes.spec.js
- packages/gafl-webapp-service/src/routes/__tests__/next-page.spec.js
- packages/gafl-webapp-service/src/routes/misc-routes.js
- packages/gafl-webapp-service/src/routes/next-page.js
- packages/gafl-webapp-service/src/server.js
- packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
- packages/gafl-webapp-service/src/session-cache/session-manager.js
https://eaflood.atlassian.net/browse/IWTF-3111
This PR refactors internal redirects to use a new redirectWithLanguageCode function on the response toolkit. This function allows us to call a redirect for the correct language without having to also call addLanguageCodeToUri each time.  This approach was initially demoed in https://github.com/DEFRA/rod-licensing/pull/1514 but this PR handles the implementation of the function and rolling it out to the rest of the app.
> Refactor redirects to automatically use correct language

- packages/gafl-webapp-service/src/processors/__tests__/uri-helper.spec.js
- packages/gafl-webapp-service/src/processors/uri-helper.js
https://eaflood.atlassian.net/browse/IWTF-3111
Testing revealed that the links to accept and reject cookies were failing when the language was set to Welsh. This turned out to be because multiple `lang` parameters were being added - for example, `/buy?lang=cy&lang=cy`
We don't want this to happen, so this PR changes the addLanguageCodeToUri function to exit early if the URI provided already has a language code.
> Stop language parameters from being duplicated in URLs

- packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
- packages/sales-api-service/src/services/transactions/create-transaction.js
There's an error after the Ts&Cs page when purchasing a licence, after the latest change in IWTF-3184. This is due to there being no permit being attached to the permission passed to the cost calculator
> Error after Ts&Cs page purchasing licence

- packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
- packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
- packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
- packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
- packages/sales-api-service/src/services/transactions/create-transaction.js
- packages/sales-api-service/src/services/transactions/process-transaction-queue.js
https://eaflood.atlassian.net/browse/IWTF-3187
Update transaction journal creation to use new price calculation in business rules lib
Also, a bit of tidying up of code written for previous tickets and a bug fix for the order complete page where prices that had pence were displaying without a trailing zero when they only had one decimal digit (e.g. 49.50 displaying as 49.5)
> Update transaction journal to use new price

- packages/gafl-webapp-service/src/pages/macros/pricing-summary.njk
https://eaflood.atlassian.net/browse/IWTF-3277
The pricing summary module should display licences with no cost as free, rather than as £0.
> Display price as free rather than £0

- packages/business-rules-lib/src/util/ages.js
- packages/sales-api-service/src/services/permissions.service.js
https://eaflood.atlassian.net/browse/IWTF-3324
The end date calculation for a permission is going wrong after the change to BST, where it is going back an extra day. This is because the permission start date is set as midnight in the locale time, which is 11pm the day before in GMT, and the end date calculation takes the last minute of the previous date. Therefore '2023-03-31T23:00:00.000Z', which is '2023-04-01T00:00:00.000+01:00' is resulting in an end date of '2023-03-30T23:59:00.000Z'. It should actually be
'2023-03-31T22:59:00.000Z', or '2023-03-31T23:59:00.000+01:00'.
> Amend permission end date to use locale time

- packages/pocl-job/src/__tests__/pocl-processor.spec.js
- packages/pocl-job/src/pocl-processor.js
https://eaflood.atlassian.net/browse/IWTF-3319
The Post Office SFTP server has been decommissioned and this is causing the POCL process to fall over every day. This change will stop the SFTP check taking place.
> Stop checking SFTP

- packages/gafl-webapp-service/src/locales/cy.json
- packages/gafl-webapp-service/src/locales/en.json
https://eaflood.atlassian.net/browse/IWTF-3367
This PR removes a sentence from the address lookup page that was causing confusion for users without posted licences.
> Remove text from address lookup page

- packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
- packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk
- packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
https://eaflood.atlassian.net/browse/IWTF-3316
This fixes a bug in multibuy where we were only displaying the catch return info on the order complete page if the most recently added licence was for salmon fishing.
This info should be displayed if any of the licences added are for salmon fishing, not just the latest one.
> Display catch return info if any salmon licences are purchased

- scripts/github/deploy.sh
There is a long standing problem where if any tags are created starting with v, w, x, y or z they'll cause the versioning script to break, as it relies on alphabetical order to grab the last version. For example, if a tag is created 'youreIt', this comes after all standard version tags (v1.32.0-rc.1) in alphabetical order. To fix this we can pipe the versions through a grep that'll elimate all non-version tagS
> Fix no tags after v

- packages/gafl-webapp-service/src/__tests__/plugin.spec.js
- packages/gafl-webapp-service/src/constants.js
- packages/gafl-webapp-service/src/handlers/__tests__/__snapshots__/page-handler.spec.js.snap
- packages/gafl-webapp-service/src/handlers/__tests__/check-analytics-handler.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
- packages/gafl-webapp-service/src/handlers/analytics-handler.js
- packages/gafl-webapp-service/src/handlers/page-handler.js
- packages/gafl-webapp-service/src/plugins.js
- packages/gafl-webapp-service/src/server.js
https://eaflood.atlassian.net/browse/IWTF-3566
When users accept tracking and hide banner the page tracks each refresh page view.
> Fix double count of page views from analytics banner

- packages/gafl-webapp-service/src/processors/__tests__/payment.spec.js
- packages/gafl-webapp-service/src/processors/payment.js
- packages/gafl-webapp-service/src/services/payment/__test__/data/mock-transaction.js
https://eaflood.atlassian.net/browse/IWTF-3543
If a user is buying on behalf of someone else, we do not want to pre-populate GOV.UK Pay fields with the licensee info, as the person who is buying on behalf may be paying instead.
This PR changes the code to only pre-populate those fields when a user is buying a single licence for themself.
It also includes some test refactoring for the payment processor to bring it more in line with the rest of the test suite.
> Only prefill payment details when user buys for themself

- packages/gafl-webapp-service/src/processors/__tests__/renewals-write-cache.spec.js
- packages/gafl-webapp-service/src/processors/renewals-write-cache.js
https://eaflood.atlassian.net/browse/IWTF-3614
This is causing a bug which causes easy renewals for contacts who have already got this field set in the CRM to fail, as the Sales API does not expect to be receiving the field in the data from the GAFL Web App.
By not copying the field when we do an easy renewal, we can leave the Sales API to assign the field itself as appropriate.
> Stop easy renewals from copying shortTermPreferredMethodOfConfirmation

- packages/sales-api-service/src/schema/validators/__tests__/validators.spec.js
- packages/sales-api-service/src/schema/validators/validators.js
https://eaflood.atlassian.net/browse/IWTF-3418
Permissions generated through the POCL process should not require concession proof.
> Stop Sales API requiring concession proof for PO entries

- Dockerfile.base
- Dockerfile.build
- docker/README.md
This PR changes the Node image we are using to run 18.17 instead, as well as a minor tweak to the Python installation as a result of the new image.
> Fix Docker for Node v18.17

- packages/gafl-webapp-service/src/handlers/__tests__/__snapshots__/page-handler.spec.js.snap
- packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
- packages/gafl-webapp-service/src/handlers/page-handler.js
- packages/gafl-webapp-service/src/pages/layout/layout.njk
https://eaflood.atlassian.net/browse/IWTF-3674
This change makes sure that the correct language tags are applied to the HTML depending on whether the page is in English or Welsh. It also adds attributes to the language switch links to make sure those are always tagged with the correct language.
> Specify language in HTML tags

- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-sales-api-failure.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/controller-handler.spec.js
- packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/date-of-birth.spec.js
- packages/gafl-webapp-service/src/pages/concessions/disability/__tests__/disability-concession.spec.js
- packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry.spec.js
- packages/gafl-webapp-service/src/pages/contact/address/lookup/__tests__/address-lookup.spec.js
- packages/gafl-webapp-service/src/pages/contact/address/select/__tests__/address-select.spec.js
- packages/gafl-webapp-service/src/pages/contact/contact/__tests__/contact.spec.js
- packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/licence-confirmation-method.spec.js
- packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/licence-fulfilment.spec.js
- packages/gafl-webapp-service/src/pages/contact/name/__tests__/name.spec.js
- packages/gafl-webapp-service/src/pages/contact/newsletter/__tests__/newsletter.spec.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-length/__tests__/licence-length.spec.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/__tests__/licence-start-time.spec.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/licence-to-start.spec.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-type/__tests__/licence-type.spec.js
- packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
- packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
- packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
- packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions.spec.js
- packages/gafl-webapp-service/src/processors/__tests__/uri-helper.spec.js
- packages/gafl-webapp-service/src/processors/uri-helper.js
- packages/gafl-webapp-service/src/routes/__tests__/misc-routes.spec.js
- packages/gafl-webapp-service/src/routes/__tests__/new-transaction-route.spec.js
- packages/gafl-webapp-service/src/server.js
- packages/gafl-webapp-service/src/session-cache/__tests__/cache-manager.spec.js
- packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
https://eaflood.atlassian.net/browse/IWTF-3673
This change fixes an accessibility issue in which the #main-content fragment, which was applied when a user selected the 'Skip to main content' link, was then applied to all subsequent pages in the journey. This is because the 302 redirects always preserved the existing fragment.
As other possible solutions like updating the action tag then broke the language param, we decided to fix this by making sure a blank fragment is applied on redirects to override #main-content.
> Stop redirect from always preserving skip link fragment

- packages/gafl-webapp-service/gafl-jest-matchers.js
- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-sales-api-failure.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/controller-handler.spec.js
- packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/date-of-birth.spec.js
- packages/gafl-webapp-service/src/pages/concessions/disability/__tests__/disability-concession.spec.js
- packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry.spec.js
- packages/gafl-webapp-service/src/pages/contact/address/lookup/__tests__/address-lookup.spec.js
- packages/gafl-webapp-service/src/pages/contact/address/select/__tests__/address-select.spec.js
- packages/gafl-webapp-service/src/pages/contact/contact/__tests__/contact.spec.js
- packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-confirmation-method/__tests__/licence-confirmation-method.spec.js
- packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/licence-fulfilment.spec.js
- packages/gafl-webapp-service/src/pages/contact/name/__tests__/name.spec.js
- packages/gafl-webapp-service/src/pages/contact/newsletter/__tests__/newsletter.spec.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-length/__tests__/licence-length.spec.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/__tests__/licence-start-time.spec.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/licence-to-start.spec.js
- packages/gafl-webapp-service/src/pages/licence-details/licence-type/__tests__/licence-type.spec.js
- packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
- packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
- packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
- packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions.spec.js
- packages/gafl-webapp-service/src/routes/__tests__/misc-routes.spec.js
- packages/gafl-webapp-service/src/routes/__tests__/new-transaction-route.spec.js
- packages/gafl-webapp-service/src/session-cache/__tests__/cache-manager.spec.js
- packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
https://eaflood.atlassian.net/browse/IWTF-3759
This adds a custom matcher to clean up the tests as discussed in https://github.com/DEFRA/rod-licensing/pull/1799
> Add custom matcher for paths with possible empty fragment

- packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
https://eaflood.atlassian.net/browse/IWTF-3677
This was a hangover from a previous version of the page and the `selectText` has since been refactored out.
> Remove unnecessary fieldset

- packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk
- packages/gafl-webapp-service/src/pages/macros/standard-form.njk
https://eaflood.atlassian.net/browse/IWTF-3676
> Remove erroneous fieldset and fix aria description

- packages/gafl-webapp-service/src/handlers/__tests__/__snapshots__/page-handler.spec.js.snap
- packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
- packages/gafl-webapp-service/src/handlers/page-handler.js
- packages/gafl-webapp-service/src/pages/layout/layout.njk
- packages/gafl-webapp-service/src/processors/__tests__/page-language-helper.spec.js
- packages/gafl-webapp-service/src/processors/page-language-helper.js
- packages/gafl-webapp-service/src/routes/__tests__/misc-routes-handlers.spec.js
- packages/gafl-webapp-service/src/routes/misc-routes.js
https://eaflood.atlassian.net/browse/IWTF-3674
This change makes sure we also apply the correct html lang tag to pages that don't use the pageHandler, like the privacy policy.
> Apply correct html lang to static pages also

- packages/business-rules-lib/package-lock.json
- packages/connectors-lib/package-lock.json
- packages/dynamics-lib/package-lock.json
- packages/fulfilment-job/package-lock.json
- packages/gafl-webapp-service/build/gulpfile.cjs
- packages/gafl-webapp-service/package-lock.json
- packages/gafl-webapp-service/package.json
- packages/payment-mop-up-job/package-lock.json
- packages/pocl-job/package-lock.json
- packages/sales-api-service/package-lock.json
- packages/sqs-receiver-service/package-lock.json
https://eaflood.atlassian.net/browse/IWTF-3735
The node-sass package is long-deprecated so it's time to switch to sass. This includes updating gulp-sass and making some very minor tweaks to the config.
> Switch from node-sass to sass

- docker/env/gafl_webapp.env.example
- packages/gafl-webapp-service/src/__tests__/server.spec.js
- packages/gafl-webapp-service/src/handlers/__tests__/__snapshots__/page-handler.spec.js.snap
- packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
- packages/gafl-webapp-service/src/handlers/page-handler.js
- packages/gafl-webapp-service/src/pages/layout/layout.njk
- packages/gafl-webapp-service/src/routes/__tests__/misc-routes-handlers.spec.js
- packages/gafl-webapp-service/src/routes/misc-routes.js
- packages/gafl-webapp-service/src/server.js
https://eaflood.atlassian.net/browse/IWTF-3732
This PR adds the snippet for Google Tag Manager to the default layout. This snippet should only be inserted when the container ID is present.
> Insert Google Tag Manager snippet in template

- packages/gafl-webapp-service/src/plugins.js
https://eaflood.atlassian.net/browse/IWTF-3865
Add region1.google-analytics.com domain, plus any others that're necessary, to the Content Policy
> Add necessary domains for GA4 to Content Policy

- packages/gafl-webapp-service/src/processors/__tests__/payment.spec.js
- packages/gafl-webapp-service/src/processors/payment.js
https://eaflood.atlassian.net/browse/IWTF-3434
Mop-up ticket for various issues with applying the cost increase:
- incorrect price displayed on licence type page for licenses starting in 30 minutes that cross the price increase threashold
- incorrect price sent to GovPay
> Permit cost increase

- packages/business-rules-lib/src/util/__tests__/permissions.spec.js
- packages/business-rules-lib/src/util/permissions.js
- packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
- packages/sales-api-service/src/services/transactions/process-transaction-queue.js
https://eaflood.atlassian.net/browse/IWTF-3932
Fix the problem where, when buying a twelve month licence to start in 30 minutes, where the price hasn’t yet gone up but will have done by the time the licence starts, the current (lower) price is quoted and charged, but the higher price is recorded in the CRM.
> Fix wrong price in CRM

- packages/gafl-webapp-service/src/locales/cy.json
- packages/gafl-webapp-service/src/locales/en.json
- packages/gafl-webapp-service/src/pages/macros/standard-form.njk
https://eaflood.atlassian.net/browse/IWTF-3824
A recent accessibility assessment identified a number of issues. This ticket is to make the Page titles meet the criteria of the WCAG 2.1 criteria. The issue and suggested solution is detailed on page 91-93 of the DAC Assessment.
This issue affects all users, but in particular, screen reader users who are dependant on having unique and accurate page titles to orient themselves within the
service.
> Improving usability to page title to meet WGAC 2.1 criteria

- packages/business-rules-lib/src/constants.js
- packages/sales-api-service/src/__mocks__/test-data.js
- packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
- packages/sales-api-service/src/services/transactions/process-transaction-queue.js
https://eaflood.atlassian.net/browse/IWTF-3834
We don't want to create new FulfilmentRequest objects in the CRM once the switchover date has passed. This PR adds the date and also updates our transaction queue logic to factor that date in when creating entities.
> Check if the fulfilment switchover date has passed when processing transactions

- packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk
https://eaflood.atlassian.net/browse/IWTF-4023
The word “Warning” is assistive text only and but is currently visible to users as main content.
> Warning message assistive text

- packages/gafl-webapp-service/package-lock.json
- packages/gafl-webapp-service/src/pages/contact/address/select/address-select.njk
https://eaflood.atlassian.net/browse/IWTF-3838
A recent accessibility assessment identified a number of issues. This ticket is to make keyboard focus consistent on Change links with the GOV.UK Design System. The issue and suggested solution is detailed on page 118-119 of the DAC assessment.
This affects keyboard only users, as this link was styled inconsistently from other links, using the browser default styling. It now uses the yellow and black, thick underline, styling used everywhere else.
> Keyboard focus inconsistency

- packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
- packages/gafl-webapp-service/src/pages/licence-details/no-licence-required/no-licence-required.njk
- packages/gafl-webapp-service/src/pages/payment/cancelled/payment-cancelled.njk
- packages/gafl-webapp-service/src/pages/payment/failed/payment-failed.njk
- packages/gafl-webapp-service/src/pages/recurring-payments/set-up-payment/set-up-payment.njk
- packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk
- packages/gafl-webapp-service/src/pages/terms-and-conditions/terms-and-conditions.njk
https://eaflood.atlassian.net/browse/IWTF-3833
This ticket is to reposition Continue button outside the field set. The issue and suggested solution is detailed on page 110-111 of the DAC assessment.
On the ‘Find your address’ page, the ‘Continue’ submit button for the form has been included inside the fieldset.
This affects screen reader users as screen readers announce the start and end of fieldsets, in order to assist the user in understanding the structure of the page. Including the ‘Continue’ button within the group could lead to the implication that the button is part of the question, not a means of submitting the form.
> Remove "Continue" button from within the fieldset

- packages/gafl-webapp-service/src/locales/cy.json
- packages/gafl-webapp-service/src/locales/en.json
- packages/gafl-webapp-service/src/pages/guidance/refund-policy.njk
https://eaflood.atlassian.net/browse/IWTF-3662
This ticket's purpose is to add an email to the refund policy page, to allow users to request a refund by email. There is no risk of refund being refused for the user because the email sent date is taken as the being within the 14 day refund period - not the ‘read by staff’ date.
> Amend refund policy page

- packages/dynamics-lib/src/queries/__tests__/fulfilment.queries.spec.js
- packages/dynamics-lib/src/queries/fulfilment.queries.js
- packages/fulfilment-job/src/staging/create-part-files.js
https://eaflood.atlassian.net/browse/IWTF-4101
The fuilfilment job doesn't handle the new fulfilment requests generated by the CRM. We don't want it to, it should ignore these, but at the moment the job throws and error and falls over which also isn't what we want
> Fix error generating fulfilment file after CRM fulfilment requests

- packages/dynamics-lib/src/queries/__tests__/permission.queries.spec.js
- packages/dynamics-lib/src/queries/permission.queries.js
https://eaflood.atlassian.net/browse/IWTF-4017
This is required for IWTF-4017 as we will need a new function within the Sales API to retrieve data about a permission based on its full reference number. See https://github.com/DEFRA/rod-licensing/pull/1957 for further implementation.
> Add new query based on full reference number

- packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
- packages/connectors-lib/src/sales-api-connector.js
https://eaflood.atlassian.net/browse/IWTF-4017
This is required for IWTF-4017 as we will need a new function within the Sales API to prepare data for a recurring payment. The recurring payment job needs to be able to conenct to this new feature so this PR updates the connector. See https://github.com/DEFRA/rod-licensing/pull/1957/ for further implementation.
> Add new route to Sales API connector

- packages/gafl-webapp-service/src/locales/en.json
https://eaflood.atlassian.net/browse/IWTF-4144
In the conditions page, enforcement officers is incorrectly referenced as "entitlement officers".
> Correcting spelling error on conditions page

- packages/gafl-webapp-service/src/locales/en.json
https://eaflood.atlassian.net/browse/IWTF-4176
The second sentence should begin ‘This fails WCAG 2.1’, not ‘This fails WCA 2.1’.
> Correcting spelling error in accessibility statement

- packages/gafl-webapp-service/src/processors/__tests__/recurring-pay-helper.spec.js
- packages/gafl-webapp-service/src/processors/recurring-pay-helper.js
https://eaflood.atlassian.net/browse/IWTF-4066
Anglers under 17 y/o should not be offered the option to set up recurring payments, so it the option has been hidden.
> Hide RCP option for Junior licence purchases

- packages/gafl-webapp-service/src/locales/cy.json
- packages/gafl-webapp-service/src/locales/en.json
https://eaflood.atlassian.net/browse/IWTF-4208
Service name in English was incorrect.
Furthermore, despite not being part of this ticket, but being in the same scope, the Welsh translation was also corrected to match the English better.
> Correcting Cookie Banner Service Name

- packages/gafl-webapp-service/src/locales/cy.json
- packages/gafl-webapp-service/src/locales/en.json
https://eaflood.atlassian.net/browse/IWTF-4241
Now that we have usefully migrated our postal licence from Paragon to Notify, we need to update the banner on our service on the buy/fulfilment page.
> Update postal fulfilment information banner

- packages/gafl-webapp-service/src/pages/guidance/recurring-payment-terms-conditions.njk
https://eaflood.atlassian.net/browse/IWTF-4244
The sub-headings `Cancel by phone or email` and `Cancel through your bank` are supposed to be visually smaller than the headings, but are appearing the same size.
This ticket is just to adjust them a slightly with a shrinking potion 🧪 
Also took the time to ensure all closing tags matched the opener tags.
> RCP T&C - Shrink Subheadings

- packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-recurring-payments.spec.js
- packages/gafl-webapp-service/src/handlers/agreed-handler.js
https://eaflood.atlassian.net/browse/IWTF-4352
On return from GovPay, the transaction is not retrieved and the transaction id has changed
> Fix bug where transaction id is not recognised

- packages/gafl-webapp-service/Dockerfile
- packages/gafl-webapp-service/package.json
allow build to pass, install dependencies then prune production
> Building tag error

- packages/dynamics-lib/src/index.js
- packages/dynamics-lib/src/queries/__tests__/activity.queries.spec.js
- packages/dynamics-lib/src/queries/activity.queries.js
https://eaflood.atlassian.net/browse/IWTF-4329
Create activity in CRM
> Create activity in CRM

- docker/env/pocl_job.env.example
- packages/pocl-job/README.md
https://eaflood.atlassian.net/browse/IWTF-4279
remove references too ftp POCL env variables
> FTP POCL references

- packages/dynamics-lib/src/entities/__tests__/recurring-payment.entity.spec.js
- packages/dynamics-lib/src/entities/recurring-payment.entity.js
- packages/sales-api-service/src/services/__tests__/__snapshots__/recurring-payments.service.spec.js.snap
- packages/sales-api-service/src/services/__tests__/recurring-payments.service.spec.js
- packages/sales-api-service/src/services/recurring-payments.service.js
- packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
- packages/sales-api-service/src/services/transactions/process-transaction-queue.js
https://eaflood.atlassian.net/browse/IWTF-4262
After a successful payment, when the permission is provisioned, a RCP record should be created along with everything else. It shouldn't be created if the RCP toggle is off
> Create RP Record in CRM

- packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
https://eaflood.atlassian.net/browse/IWTF-3913
On the licence to start page, if no option is selected, the select an option error doesn't appear in the error summary box
> Licence to start error not in error summary

- packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/route.spec.js
- packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk
- packages/gafl-webapp-service/src/pages/renewals/identify/route.js
https://eaflood.atlassian.net/browse/IWTF-3913
The inline error for date of birth on the renewals identity page is missing, it's only presented in the error summary box
> Missing inline error on renewals id page

- packages/gafl-webapp-service/src/locales/cy.json
- packages/gafl-webapp-service/src/locales/en.json
- packages/gafl-webapp-service/src/processors/__tests__/pricing-summary.spec.js
- packages/gafl-webapp-service/src/processors/pricing-summary.js
https://eaflood.atlassian.net/browse/IWTF-4385
Edge case for completing purchase before price changes
> Payment edge case 2025

- packages/dynamics-lib/src/entities/__tests__/permission.entity.spec.js
- packages/dynamics-lib/src/entities/permission.entity.js
- packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
- packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
https://eaflood.atlassian.net/browse/IWTF-4265
Now that the recurring payment status is saved to the CRM, we can use that data to conditionally display content relating to recurring payments.
> Update order complete page RCP logic

- packages/gafl-webapp-service/src/locales/cy.json
- packages/gafl-webapp-service/src/locales/en.json
- packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk
https://eaflood.atlassian.net/browse/IWTF-4414
Change link to [this](https://www.gov.uk/government/collections/fisheries-annual-reports) so we won't have to change it in the future 
Also added reference to England as the reports only cover England
> Incorrect Link to Fisheries Report

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-4364
Error message when no radio is selected was appearing in English when lang=cy. This ticket just adds in the Welsh.
It should be noted that the radios on the Newsletter page come preselected, so facing this error is unlikely.
> Add Missing Welsh to Newsletter Page

- packages/gafl-webapp-service/assets/sass/rod-licensing/_calendar.scss
- packages/gafl-webapp-service/assets/sass/rod-licensing/_general.scss
- packages/gafl-webapp-service/src/pages/macros/standard-form.njk
https://eaflood.atlassian.net/browse/IWTF-4379
https://eaflood.atlassian.net/browse/IWTF-4380
Pricing summary appears beneath green button.
This means that if a user doesn't scroll down, they will miss them and may not know the licence price to make an informed decisions until further into the journey. This may result in a user clicking back and forth through the journey rather than proceeding smoothly through.
> Move continue button to below the pricing summary

- docker/env/recurring_payments_job.env.example
- docker/env/recurring_payments_job.secrets.env.example
- packages/recurring-payments-job/src/__tests__/recurring-payments-processor.spec.js
- packages/recurring-payments-job/src/recurring-payments-processor.js
- packages/recurring-payments-job/src/services/__tests__/govuk-pay-service.spec.js
- packages/recurring-payments-job/src/services/govuk-pay-service.js
https://eaflood.atlassian.net/browse/IWTF-3657
Once the new permission has been provisioned, we are ready to request the next payment from GOV.UK Pay.
> Recurring payment job sends payment requests to GOV.UK Pay

- packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
- packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
https://eaflood.atlassian.net/browse/IWTF-4265
When checking on the order complete page if the new licence has a recurring payment agreement, base this off the existence of an agreementId on the transaction rather than trying to get it from the permission.
> Check recurring status based on transaction

- packages/recurring-payments-job/src/__tests__/recurring-payments-processor.spec.js
- packages/recurring-payments-job/src/recurring-payments-processor.js
https://eaflood.atlassian.net/browse/IWTF-4516
We want the transaction created for a recurring payment to contain a reference to the recurring payment
So that we are able to update the existing recurring payment and create a follow-on payment once a new Permission is provisioned
The createNewTransaction function in recurring-payments-processor adds the agreement id to the transaction.
> Amend recurring payment transaction to contain reference to recurring payment

- packages/gafl-webapp-service/src/locales/cy.json
- packages/gafl-webapp-service/src/locales/en.json
- packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
- packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
- packages/gafl-webapp-service/src/pages/payment/cancelled/__tests__/route.spec.js
- packages/gafl-webapp-service/src/pages/payment/cancelled/payment-cancelled.njk
- packages/gafl-webapp-service/src/pages/payment/cancelled/route.js
- packages/gafl-webapp-service/src/pages/payment/failed/__tests__/route.spec.js
- packages/gafl-webapp-service/src/pages/payment/failed/payment-failed.njk
- packages/gafl-webapp-service/src/pages/payment/failed/route.js
- packages/gafl-webapp-service/src/processors/__tests__/recurring-pay-helper.spec.js
- packages/gafl-webapp-service/src/processors/recurring-pay-helper.js
https://eaflood.atlassian.net/browse/IWTF-4514
When a user decides to set up a recurring payment agreement but then cancels the first payment, or the first payment fails, we want to include additional text on the cancel or failure page to confirm that they have not finished setting up the agreement for future payments.
This includes a bit of refactoring to use some existing logic from the order complete page.
> Clarify RP agreement status when first payment does not go through

- packages/gafl-webapp-service/src/locales/cy.json
https://eaflood.atlassian.net/browse/IWTF-4518
Welsh translation for junior hint text was not included on licence type selection page.
> Missing Welsh from Licence-type selection page

- packages/sales-api-service/src/schema/__tests__/recurring-payments.schema.spec.js
- packages/sales-api-service/src/schema/recurring-payments.schema.js
- packages/sales-api-service/src/server/routes/__tests__/recurring-payments.spec.js
- packages/sales-api-service/src/server/routes/recurring-payments.js
https://eaflood.atlassian.net/browse/IWTF-4640
The new routes added to the Sales API for recurring payments should have proper validation.
> Add validation schemas to recurring payment routes

- packages/dynamics-lib/src/queries/__tests__/recurring-payments-queries.spec.js
https://eaflood.atlassian.net/browse/IWTF-4513
This test was written on one branch while the defra_lastdigitscardnumbers field was being added on another, so once they were merged it failed.
> Fix field names in test

- packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
https://eaflood.atlassian.net/browse/IWTF-3433
Remove the logging code added in commit #be1956e / bugfix/iwtf-3338-new-cost-start-date once it’s no longer needed.
PR for when logging was added : https://github.com/DEFRA/rod-licensing/pull/1674
> Remove logging code for new prices bug

- packages/sales-api-service/src/services/__tests__/__snapshots__/recurring-payments.service.spec.js.snap
- packages/sales-api-service/src/services/__tests__/recurring-payments.service.spec.js
- packages/sales-api-service/src/services/recurring-payments.service.js
https://eaflood.atlassian.net/browse/IWTF-4701
Currently the name field of RecurringPayments in the CRM is not set to anything useful. We want it to include the contact name and the year the next payment is due to make it easier to find records in the interface.
> Set name of RecurringPayment record

- packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js
- packages/gafl-webapp-service/src/services/payment/govuk-pay-service.js
https://eaflood.atlassian.net/browse/IWTF-4351
This removes the card_details from the logs when we are checking the payment status from GOV.UK Pay.
> Sanitise payment details in logging

- packages/dynamics-lib/src/__mocks__/option-set-data.json
- packages/dynamics-lib/src/entities/__tests__/recurring-payment.entity.spec.js
- packages/dynamics-lib/src/entities/recurring-payment.entity.js
https://eaflood.atlassian.net/browse/IWTF-4658
The name of the field is defra_cancelledreason, but the name of the optionset is defra_cancelledreasons.
> Fix name of cancelledreasons optionset

- packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk
https://eaflood.atlassian.net/browse/IWTF-4720
On the renewal journey, on mobile phone view - the text box is too long compared to the other text boxes, this may encourage people to enter more than just the last 6 digits.
> Make reference number entry box on renewal journey smaller

- packages/recurring-payments-job/src/services/__tests__/govuk-pay-service.spec.js
- packages/recurring-payments-job/src/services/govuk-pay-service.js
https://eaflood.atlassian.net/browse/IWTF-4648
If the Pay API cannot find the agreement_id, it returns a message saying that it couldn’t find a match. This should be logged for further investigation
> Log when GOV.UK Pay cannot find an Agreement ID

- packages/sales-api-service/src/services/__tests__/recurring-payments.service.spec.js
- packages/sales-api-service/src/services/recurring-payments.service.js
https://eaflood.atlassian.net/browse/IWTF-4806
Previously, creation of a new recurring payment agreement was limited so that the start date could not be more than 30 days after the issue date. If that were the case, creation of the new records in the CRM would fail. Earlier validation in the new licence journey should have prevented anyone from getting into that situation anyway.
However, in some edge cases, it's possible that a user going through the easy renewals journey very early (more than 30 days before expiry) could try to set up a recurring payment agreement for a licence starting more than 30 days after the issue date. This would then silently fail and not show up in the CRM.
This PR removes the 30-day limit on the start date when setting up new recurring payment agreements on …
> Allow RCP agreements to be created through easy renewal with later date

- packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/__snapshots__/route.spec.js.snap
- packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/route.spec.js
- packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
https://eaflood.atlassian.net/browse/IWTF-4719
Licence summary page address country appears in capitals when should only be first letter
> Country capital letters
